### ISSUE TITLE
[Question] How to output generated files into specific folder 

### ISSUE THREAD

**Issue by amadeu01** [comigor/artemis#10]
Hi, 
I would like to output my `.g.dart` and `.dart` files into `generated/` folder.
Is it possible to do so? How can I do it?

**Comment by comigor** [comment]
Hi @amadeu01,
That's definitely something I'll do soon, but that's not possible yet.

**Comment by comigor** [comment]
When looking at https://github.com/comigor/artemis/issues/11, I found out `build` forces builders to write outputs to specific folder (it depends on the synthetic asset you use `lib`, `test` or `web`).

So unless `generated/` folder lives inside `lib/`, it won't be possible to generate files to that folder.

But I'll soon give options to customize output folder.

**Comment by comigor** [comment]
Update: it seems [build doesn't allow generating files to custom folders](https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md#output-restrictions).
I'll try circumventing that by creating an aggregate builder that generate to a single file, but this will be a breaking change.

**Comment by amadeu01** [comment]
@comigor I don't know whether this will work, but I managed to create a file with different name from the input by adding it to `buildExtensions`

```dart
Map<String, List<String>> get buildExtensions => const <String, List<String>>{
        '.env': <String>['dot_env.dart']
      };
```

maybe, and that is a big maybe, you can use `generated/dot_env.dart`

I'll try it latter.

**Comment by comigor** [comment]
I'm working on it! When you use the `$lib$` synthetic input, it's possible to read and write to almost all folders. But, as a downside, you need to specify exactly the outputs at compile time.

Well, soon I'll have some news, but I guarantee it will be a breaking change :P
