### ISSUE TITLE
fragments glob for two separated files - bad state no element

### ISSUE THREAD

**Issue by vasilich6107** [comigor/artemis#105]
If I create the `common.graphql` for fragments and refer from two different files to the fragments from `common.graphql` i'll get the next error - https://tppr.me/X9tyQ

I'll try to fix this this and cover with tests)

**Comment by vasilich6107** [comment]
Got the test https://tppr.me/YVjqr

**Comment by vasilich6107** [comment]
it seems that this bug relates only to my dirty fix branch

**Comment by comigor** [comment]
Oh, have you had any luck? Still hadn't time to do anything on Artemis those last weeks :(

**Comment by vasilich6107** [comment]
It was just a bug in my `ditrty/dedup-fix`
I applied additional updates to improve this)
https://github.com/comigor/artemis/commit/0ce4dddbbc46ed1d9304d0a83b7a655b47aa75aa

Sorry for disturbing.
