### ISSUE TITLE
Complex input will generate wrong argument type

### ISSUE THREAD

**Issue by agent3bood** [comigor/artemis#108]
I have tried to generate the error using the pokemon example from the this repo.
the schema:
https://github.com/agent3bood/artemis/blob/master/example/pokemon/pokemon.schema.graphql#L96
the query:
https://github.com/agent3bood/artemis/blob/master/example/pokemon/graphql/complex_query.query.graphql
the generated input type is wrong:
https://github.com/agent3bood/artemis/blob/master/example/pokemon/lib/graphql/complex_query.graphql.dart#L59
it is 
`final List<ComplexQuery$Query> input;`
which should be 
`final List<ComplexQuery$complexObjects> input;`

**Comment by szediwy** [comment]
Did you find a workaround?

**Comment by agent3bood** [comment]
No, maybe try another library like https://github.com/gql-dart/gql (not sure if it works)

**Comment by vasilich6107** [comment]
@szediwy @agent3bood this was fixed long time ago I just forgot to mention that
As far as input objects have unique names we generate the corresponding classes for them
