### ISSUE TITLE
Fragment calling another fragment

### ISSUE THREAD

**Issue by SwannLV** [comigor/artemis#114]
**Bug description**
My query uses a fragment. This fragment also uses another fragment.
When I generate the types, I can see both fragments mixins, but the second one is not used anywhere.

So when I try to use generated types to parse my json, properties from second mixin are not available.

Thank you very much :)

**Specs**
Artemis version: 6.0.2-beta.1

**Comment by comigor** [comment]
Hey there @SwannLV!

Could you point to a schema/query example so I can debug further? There's a [test case with exactly this behavior](https://github.com/comigor/artemis/blob/beta/test/query_generator/fragments/fragment_on_fragments_test.dart) and it's working on latest beta version!

**Comment by SwannLV** [comment]
Hello!

This test is a great base for me to explain.
Fragment spread on another fragment is working.
But what is not working is when I do:
`final pokemon = Query$Query$Pokemon.fromJson(myJson);`

`pokemon.id` will be defined, but not `pokemon.name` nor `pokemon.number` (from `PokemonPartsMixin`)

=> `PokemonPartsMixin` is used nowhere in thee generated code, I would believe that `PokemonPartsMixin` would be part of `Query$Query$Pokemon`:

`class Query$Query$Pokemon with EquatableMixin, PokemonMixin, PokemonPartsMixin`

Hoping having been clear enough ^^
Thanks again!

**Comment by comigor** [comment]
Oh, you're absolutely right! I'll take a look at it!

**Comment by SwannLV** [comment]
Great! It will help me a lot! Thanks

**Comment by comigor** [comment]
@SwannLV Could you try again with `6.0.4-beta.1` as soon it's released? https://github.com/comigor/artemis/pull/115

**Comment by SwannLV** [comment]
Tested. This is perfect, thanks!
