### ISSUE TITLE
Change variable name if it start with underscore. 

### ISSUE THREAD

**Issue by TarekkMA** [comigor/artemis#116]
**Bug description**
Fields starting with underscore cause issues since dart can't have private named parameters.

In the mutation/query I can alias field name to avoid the problem with fields starting with underscore. But in the input I can't do the same.

I think this issue can be solved by checking for underscore in the field name and using ``@JsonKey(name:"noUnderScoreName")`` to mitigate the issue

**Specs**
Artemis version: '>=5.0.0 <6.0.0'

```graphql
mutation addStudent($input: StudentInput){
    addStudent(input:$input){
        id:_id,
    }
}

input StudentInput {
    _id: Int
    person: PersonInput
   ...
}

input PersonInput {
    ...
}
```

**Comment by comigor** [comment]
Hello @TarekkMA!

Thanks for reporting this! It's related to https://github.com/comigor/artemis/issues/41 (in a time we were filtering out fields starting with double underscores).

**Comment by vasilich6107** [comment]
@comigor 
Hi. I have some time to work on Artemis next week.
I can implement transformations from '_variable' to '$variable' if I understood correctly the approach suggested in https://github.com/comigor/artemis/issues/41#issuecomment-541447271

**Comment by vasilich6107** [comment]
In scrope of this I would like to cover the issue when variable is called like the Dart keyword.
Here is a list https://dart.dev/guides/language/language-tour#keywords

I have an example of this edge case in enum on previous project

```
enum CompletionStatus {
    completed
    new
    saved
    unknown
}
```

**Comment by vasilich6107** [comment]
To sum up:

All items that start with underscore will be replaced by `$`

`_variable` => `$variable'
`__typename` => `$$typename'

All items matching the Dart keywords will be prepended with `$`

`new` => `$new`
`factory` => `$factory`

If you agree with this approach I'll implement it.

**Comment by comigor** [comment]
@vasilich6107 that seems the way to go!

**Comment by vasilich6107** [comment]
Small update.
In case of dart keyword match we need something more tricky)
There could be a case when the enum has `new` and `_new` at the same time so pretending keywords with $ will lead to two equal names `$new` items.

I suggest to prepend dart keywords with `kw$`
`new` -> `kw$new`

**Comment by comigor** [comment]
I think that's ok, but following this mindset, there can be both `_thing` and `__thing` fields, how would you deal with that? A dollar sign for each underscore?

I think I would just bail on fields matching keywords, suggesting to use aliases instead, but that opinion may be unpopular.

**Comment by vasilich6107** [comment]
As I wrote previously 

`_variable` => `$variable`

`__typename` => `$$typename`

**Comment by comigor** [comment]
oops, sorry, forgot about that message

yep, that seems better than the bug we have today

**Comment by vasilich6107** [comment]
I do not think that you can alias the enum item)

```
enum CompletionStatus {
    completed
    new
    saved
    unknown
}
```

**Comment by vasilich6107** [comment]
The aliasing could alway be a fallback to the case when somebody would not like the `kw$` prefix)))

**Comment by vasilich6107** [comment]
Hi @TarekkMA 
Could you try this branch while it awaits the review?
```
artemis:
    git:
      url: https://github.com/comigor/artemis.git
      ref: bugfix/underscored-items-another-solution
```

**Comment by vasilich6107** [comment]
Closed by #142

**Comment by RageshAntony** [comment]
> To sum up:
> 
> All items that start with underscore will be replaced by `$`
> 
> `_variable` => `$variable`
> 
> `__typename` => `$$typename`
> 
> All items matching the Dart keywords will be prepended with `$`
> 
> `new` => `$new`
> 
> `factory` => `$factory`
> 
> If you agree with this approach I'll implement it.

I am having  a issue in this renaming 

I am quering mongodb using graphql , so IDs are like '_id' 

These _id converted to $id , like you said 

But it also sending query in renamed variable like 

{$id: 5f660d7a929072166f5addb2}

So I am getting exception the variable not supplied 

But if I manually gave variables in WatchQueryOptions as {'_id': 5f660d7a929072166f5addb2} , query working ... 

Pls help me 

Code 

```
Future getSeries() async {
  final args = SeriesByIdArguments($id: "5f660d7a929072166f5addb2");
  final WatchQueryOptions _options = WatchQueryOptions(
      errorPolicy: ErrorPolicy.all,
      fetchResults: true,
      variables: <String, dynamic>{
        '_id': "5f660d7a929072166f5addb2", // if I gave args.toJson() , execption thrown since $id is going 
      },
      documentNode: SeriesByIdQuery(
              variables: SeriesByIdArguments($id: "5f660d7a929072166f5addb2"))
          .document);

  final client = GraphQLClient(
    cache: InMemoryCache(),
    link: HttpLink(uri: 'http://192.168.31.107:8000/graphql'),
  );

  QueryResult result = await client.query(_options);
  final series = SeriesById$Query$Series.fromJson(result.data);
  print('series ' + result.data.toString());
  print(args.toJson());
}
```

**Comment by vasilich6107** [comment]
I’ll check

**Comment by vasilich6107** [comment]
Works fine as you see with latest `artemis` - https://tppr.me/pJ1td
If you still have a problems create a new issue according to template

**Comment by RageshAntony** [comment]
> Works fine as you see with latest `artemis` beta version - https://tppr.me/pJ1td
> If you still have a problems create a new issue according to template

i already using  6.12.3-beta.2 ...But toJson printing $id only 

![image](https://user-images.githubusercontent.com/36100215/94998355-ee0a8200-05ce-11eb-85c1-8641fb6f2eca.png)

The implementation in generated class is only having $id for both fromJson and toJson 

GraphQL query:

```
query seriesById($_id: MongoID!){
    seriesById(_id: $_id){
        title
        description
        rating
        maturity
        release
        language
        seasons
        seasonsInfo{
            seasonNo
            info
            release
            episodes
            _id
        }
        episodesData{
            seasonNo
            number
            title
            desc
            airDate
            durationMins
            poster
            uri
            _id
        }
        cast{
            name
            roll
            info
            _id
        }
        studio
        videoUrl
        videoImage
        createdBy
        for
        isPaid
        categoryId
        likes
        disLikes
        views
        isDeleted
        _id
        updatedAt
        createdAt
    }
}
```

**Comment by vasilich6107** [comment]
Please create a separate issue and fill it according to template

**Comment by RageshAntony** [comment]
> Please create a separate issue and fill it according to template

yeah here 
https://github.com/comigor/artemis/issues/223
