### ISSUE TITLE
Examples in repo not working

### ISSUE THREAD

**Issue by Diligas-a** [comigor/artemis#123]
Pull repo -> delete older generated files -> pub run build_runner build
`Exception: Schema `github.schema.graphql` was not found or doesn't have a proper format!
Make sure the file exists and you've typed it correctly on build.yaml.
Bad state: No element`
![image](https://user-images.githubusercontent.com/18558839/80919408-7364de80-8d72-11ea-83fb-29acc933ee6b.png)

**Comment by vasilich6107** [comment]
You can check this one until we fix them
https://github.com/artflutter/graphql_toolchain

**Comment by comigor** [comment]
Hey @Diligas-a, how are you doing?

The Github example [won't work by default](https://github.com/comigor/artemis/tree/beta/example#github), as the Github schema file is too big (around 3MB), and I didn't want to commit it on the repository. If you provide your own on the espected path, it should compile. Refer to https://github.com/octokit/graphql-schema on how to get the schema.

And feel free to reopen this issue if you find another problem!
