### ISSUE TITLE
Custom data types in queries and mutations

### ISSUE THREAD

**Issue by stanojevicboban** [comigor/artemis#127]
Hi, I've been enjoying this tool and it's working great in retrieving data from the server.

However, I've noticed that when I have a complex query, like the one below, there are custom data types being used:

```
query Contacts($first: Int, $offset: Int, $sortBy: ContactsSortByEnum, $orderBy: OrderByEnum, $searchKeyWord: String, $criteria: FilterInput) {
...
```
In the case above, we have `OrderByEnum` which is enumeration, but the generated code looks like: 
```
final OrderByEnum orderBy;
```

Since OrderByEnum isn't defined anywhere, I need to declare it. And since the file is generated automatically, I can't edit it so I can, for example, import new dart file that has the enums declared.

Can you tell me what I'm doing wrong, and how exactly can I resolve this issue? Many thanks.

**Comment by vasilich6107** [comment]
Could you create a sample reproduction repo?
The enum types that exists in schema should be generated correctly

**Comment by stanojevicboban** [comment]
I can't put the code, since it's not my own personal, but the code snippet from schema.json looks like this, not sure if that is helpful:
```
{
          "kind": "ENUM",
          "name": "OrderByEnum",
          "description": "Specify in which order result will be return.",
          "fields": null,
          "inputFields": null,
          "interfaces": null,
          "enumValues": [
            {
              "name": "Asc",
              "description": "Sort result in ascending order.",
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "Desc",
              "description": "Sort result in descending order.",
              "isDeprecated": false,
              "deprecationReason": null
            }
          ],
          "possibleTypes": null
        },
```

**Comment by vasilich6107** [comment]
What version of Artemis are you using?

**Comment by stanojevicboban** [comment]
Currently using 2.1.4. Now this is where things become even more difficult with me.

I have schema defined in the schema.json file (make not that it is not a dart file).

So with the 2.1.4. the following:

```
schema_mapping:
   - schema: schema.json
   queries_glob: graphql/login.graphql
   output: lib/api/graphql/gql_login_api.dart
```
works just fine and it generates types correctly, but it doesn't work with enum types.

But, I see that 5.1.0 is the latest version, but using that version, it no longer accepts my json file that contains entire schema.

I am trying the solutions you have provided in the Changelog to see if I can easily fix this issue.

**Comment by vasilich6107** [comment]
You can always request SDL schema from your graphql endpoint and easily move to 6.0.6 beta

There is no reason to use v2, there were a lot of bugs fixed recently

**Comment by stanojevicboban** [comment]
Okay, lots of debugging later, and I believe I have fixed this. 

Updating to the latest version, and then converting my schema.json to schema.graphql (using perhaps this one: https://www.npmjs.com/package/graphql-json-to-sdl) helped a lot.

I am closing this one and thanking @vasilich6107 a lot for his help.

I do have another bug (recursive error during code generation) that I will have to look first in the current issue queue, and if I don't find it I will create another bug ticket.

**Comment by vasilich6107** [comment]
You can use 
https://plugins.jetbrains.com/plugin/8097-js-graphql

For fetching SDL schema from GraphQL endpoint. In addition you’ll get queries code completion.

For VSCode there is something like this

https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode
