### ISSUE TITLE
Nullable Wrapper

### ISSUE THREAD

**Issue by lucasavila00** [comigor/artemis#13]
As far as I could tell Artemis isn't doing something to address Dart's lack of non nullable types.

I couldn't see a way to deal with it using custom scalars as nullable _types_ wouldn't be addressed.

The way I work around this right now is by using [Dartz Option](https://github.com/spebbe/dartz/blob/master/lib/src/option.dart), meaning having to wrap all nullable types with a runtime check to "cast" them.

Is something like this possible?

Here is a snippet of my [current generator result](https://github.com/zino-app/graphql-flutter/issues/26#issuecomment-415974734) and how the generated code deals with it:
```graphql
query authToken {
  # authToken: String
  authToken 
}
```
```dart
// generated
import 'package:dartz/dartz.dart';

class AuthToken {
  AuthToken(this._d);
  final Map<String, dynamic> _d;

  Option<String> get authToken =>
      option<String>(this._d["authToken"] != null, this._d["authToken"]);
}
```

**Comment by comigor** [comment]
Hey @lucasavila00 
Sure, it's possible to do. This could be done as an abstraction before Dart supports non-nullable types, but I was waiting for official support to do it.

**Comment by lucasavila00** [comment]
@comigor I believe it will take some time before nnbd is released and stable.
I haven't had the time to study Artemis source code and see how to implement this feature but I'll try to do it if I have some free time.

**Comment by comigor** [comment]
@lucasavila00 We've just merged https://github.com/comigor/artemis/pull/283 with NNBD support for Artemis.
I'm closing this but feel free to open another issue, if applicable, after testing the new version `7.0.0-beta.2`.
