### ISSUE TITLE
Repeated Objects in different paths of the query are not supported

### ISSUE THREAD

**Issue by leoiacovini** [comigor/artemis#18]
When we have a Query that contains the same Object in different paths with different fields selected the generations does not work as supposed. This is a problem, especially in heavy recursive schemas. For eg:

Schema.graphql
```graphql
type MyObject {
  id: ID!
  name: String!
  number: Int!
  connections: [MyObject]
}

```

```graphql
query MyQuery {
  myObject {
    id
    connections {
      name
      number
    }
  }
}
```

Given that the Classes are generated based on the Object name, here we would have two conflicting classes of `MyObject`, with a different set of fields each.

```dart
class MyObject {
  final String id;
  final List<MyObject> connections;
}
```

and 

```dart
class MyObject {
  final String name;
  final int number;
}
```

We may have some options to solve this problem, being one of they the same strategy used by Apollo, that is creating classes taking into account the path in the query like: `MyQuery_myObject` and `MyQuery_myObject_connections`. However, this ends up creating very unreadable and long-named classes, so if possible would be great to have an alternative.

**Comment by comigor** [comment]
This is expected (for now), but we need to think about what to do?

**Comment by pd4d10** [comment]
Faced with this issue +1.

Except generating classes of different name, perhaps another way is to generate a super set of these types. Something like

```dart
class MyObject {
  final String id;
  final List<MyObject> connections;
  final String name;
  final int number;
}
```

But it would lose some type information in this way.

**Comment by comigor** [comment]
Hey @leoiacovini,

I've recently release 4.0.0 and this was probably fixed among other things! Now artemis will generate all classes with "pathes".

Feel free to reopen thiss issue if the error still happen after bumping.
