### ISSUE TITLE
Is there a way to share classes in queries?

### ISSUE THREAD

**Issue by GP4cK** [comigor/artemis#184]
In the pokemon example we have:
pokemon.schema.graphql:
```graphql
type Pokemon {
    ...
    evolutions: [Pokemon]
}
```

fragments_glob.query.graphql
```graphql
{
  pokemon(name: "Pikachu") {
    ...Pokemon
    evolutions {
      ...Pokemon
    }
  }
}
```

Yet, the generated code in 
lib/graphql/fragments_glob.dart
```dart
@JsonSerializable(explicitToJson: true)
class FragmentsGlob$Query$Pokemon
    with EquatableMixin, FragmentsGlob$PokemonMixin {
  // ...
  // Could this be a List<FragmentsGlob$Query$Pokemon> instead?
  List<FragmentsGlob$Query$Pokemon$Pokemon> evolutions;
  // ...
}
```

**Comment by vasilich6107** [comment]
Do not split between files. You'll get all code in one file with shared classes.
There is no way of sharing classes between multiple output files for now.

**Comment by GP4cK** [comment]
I tried putting the fragments and the query in the same file but I still get 2 classes:
1. FragmentsGlob$Query$Pokemon
2. FragmentsGlob$Query$Pokemon$Pokemon

I forked the repo and created a pokemon branch. It's available [here](https://github.com/GP4cK/artemis/tree/pokemon).

Here's the content of graphql/fragments_glob.query.graphql
```graphql
{
  pokemon(name: "Pikachu") {
    ...Pokemon
    evolutions {
      ...Pokemon
    }
  }
}

# copy pasted the below from graphql/fragments_glob.fragment.graphql
fragment Pokemon on Pokemon {
  id
  weight {
    ...weight
  }
  attacks {
    ...pokemonAttack
  }
}

fragment weight on PokemonDimension {
  	minimum
}

fragment pokemonAttack on PokemonAttack {
  special {
    ...attack
  }
}

fragment attack on Attack {
  name
}
```

I removed the this line in build.yaml: `fragments_glob: graphql/**.fragment.graphql`.  
And final ran `flutter pub run build_runnner build`. But in `lib/graphql/fragments_glob.graphql.dart`, I still have:

```dart
@JsonSerializable(explicitToJson: true)
class FragmentsGlob$Query$Pokemon
    with EquatableMixin, FragmentsGlob$PokemonMixin {
  FragmentsGlob$Query$Pokemon();

  factory FragmentsGlob$Query$Pokemon.fromJson(Map<String, dynamic> json) =>
      _$FragmentsGlob$Query$PokemonFromJson(json);

  List<FragmentsGlob$Query$Pokemon$Pokemon> evolutions; // why not List<FragmentsGlob$Query$Pokemon>?

  @override
  List<Object> get props => [id, weight, attacks, evolutions];
  Map<String, dynamic> toJson() => _$FragmentsGlob$Query$PokemonToJson(this);
}
```

Actually I think it might be link to this [answer](https://github.com/comigor/artemis/issues/52#issuecomment-554374118).

**Comment by vasilich6107** [comment]
I see. It seems to be an expected behaviour.
As far as fragment naming is not very easy we decided to prepend the class name with types or class names.
In your code you can refer to the classes via `FragmentsGlob$PokemonMixin` or `List<FragmentsGlob$PokemonMixin>`. I use this approach in my code
