### ISSUE TITLE
Can I add multiple queries in query.graphql file 

### ISSUE THREAD

**Issue by girirajthara** [comigor/artemis#185]
can I write both queries in one file

```graphql
query CompaniesData {
    allCompanies {
        id
        name
        industry
        __typename
    }
}

query GetEmployee{
   employee{
      id
      name
   }
}
```

**Comment by vasilich6107** [comment]
Not for now(

There is an "ugly" solution for this in PR waiting to be merged)
https://github.com/comigor/artemis/pull/158

@comigor could you help us?

**Comment by comigor** [comment]
I think it's ok to merge your PR if it doesn't rollback the performance issue you've fixed on https://github.com/comigor/artemis/pull/186

**Comment by girirajthara** [comment]
@vasilich6107  why can I expect the release?

**Comment by vasilich6107** [comment]
I'll try rebase soon

**Comment by vasilich6107** [comment]
PR is ready to be merged

**Comment by comigor** [comment]
I've just merged https://github.com/comigor/artemis/pull/158

**Comment by comigor** [comment]
@girirajthara Please test it with latest `6.6.1-beta.1` version, and thanks again @vasilich6107!

**Comment by vasilich6107** [comment]
Closing the issue as far as it was fixed long time ago)

**Comment by girirajthara** [comment]
It didn't work with fragments .But we moved to gRPC for an alternative approach

**Comment by vasilich6107** [comment]
@girirajthara please make an issue
