### ISSUE TITLE
Provide please anyMap property for json_annotation generator

### ISSUE THREAD

**Issue by fryette** [comigor/artemis#188]
Would be nice to have the possibility to customize json_annotation somehow

**Comment by comigor** [comment]
Hello @fryette!
I'm not familiar with `anyMap`, could you exemplify your use case?

**Comment by fryette** [comment]
To use generated models in the app I also want to serialize and deserialize it let say from cache service. For now, library generated models have only `explicitToJson` parameter. `toJson` and `fromJson` method works only with Map<String, dynamic>. However, e.x. you don't have always Map<String, dynamic> how to work with it? JsonAnnotation library provides `anyMap`parameter and then fromJson and toJson started work with Map<dynamic, dynamic>  instead of Map<String, dynamic>.

**Comment by comigor** [comment]
I've never encountered an use case that I didn't have a `Map<String, dynamic>` json object... but `anyMap` should do no harm, I need to check it wouldn't end up in a bizarre serialization corner case of some kind.

To understand it better, in your current use case, couldn't you convert your `Map<dynamic, dynamic>` object into `Map<String, dynamic>`?

**Comment by fryette** [comment]
Unfortunately cannot. I tried...
In my case cache service can provide only Map<dynamic, dynamic> and converting long inheritance is impossible. (When you have multiple `Map<dynamic, dynamic>` in Map<dynamic, dynamic> you need somehow handle it. That why I asking to add that flag.

**Comment by comigor** [comment]
I got you, for ease of use (and if doesn't harm), I'm ok with adding this flag.

However, I still didn't see why you can't do something like this (I know it isn't pretty, but should work):
```dart
dynamic _convertInternal(dynamic original) {
  if (original is Map) {
    return <String, dynamic>{}..addEntries(original.entries
        .map((e) => MapEntry<String, dynamic>(e.key.toString(), _convertInternal(e.value))));
  }
  return original;
}

Map<String, dynamic> convert(Map<dynamic, dynamic> original) {
  return _convertInternal(original) as Map<String, dynamic>;
}

void main() {
  final map1 = {1: 'b'};
  final map2 = {Object(): {'a': 2}};
  
  print(convert(map1).runtimeType);
  print(convert(map2).runtimeType);
}
```

**Comment by fryette** [comment]
This is what I do right now, but would be great to avoid these things.(I'm totally OK if you decide to not add `anyMap` property)
Thanks!

**Comment by vasilich6107** [comment]
@fryette did you tried to set `anyMap` option in your `build.yaml`?
https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration

**Comment by fryette** [comment]
hm....will check soon!

**Comment by vasilich6107** [comment]
@fryette any news on any map?)

**Comment by fryette** [comment]
Fixed, thx!
