### ISSUE TITLE
failed to process subscription

### ISSUE THREAD

**Issue by oofp** [comigor/artemis#216]
**Bug description**
Getting error when processing subscription
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 558ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 94ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.3s

[INFO] Running build...
[SEVERE] artemis:artemis on lib/$lib$:

NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
[INFO] Running build completed, took 142ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 73ms

[SEVERE] Failed after 232ms
pub finished with exit code 1
```

**Specs**

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: '>=5.0.0 <6.0.0'
  build_runner: ^1.5.0
  json_serializable: ^3.0.0

<details>
<summary>build.yaml:</summary>
  
```
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: lib/gql/schema.graphql
              queries_glob: lib/gql/**.gql
          generate_helpers: true
```
</details>
<details>
<summary>
[INFO] Generating build script...
[INFO] Generating build script completed, took 558ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 94ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.3s

[INFO] Running build...
[SEVERE] artemis:artemis on lib/$lib$:

NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
[INFO] Running build completed, took 142ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 73ms

[SEVERE] Failed after 232ms
pub finished with exit code 1
</summary>
  
```bash
# Please paste the output of
$ flutter pub run build_runner build --verbose
#or
$ pub run build_runner build --verbose
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
type Call {
  callID: CallID!
  localAddress: String!
  remoteAddress: String!
  callState: CallState!
}

enum CallState {
  Offered
  Ringing
  Connecting
  Connected
  Initiated
  Ringback
  Disconnected
}

type User {
  firstName: String!
  lastName: String!
  middleName: String
  userType: UserType!
}

type CallID {
  id: Int!
}

enum UserType {
  UserManager
  UserTechLead
  UserDev
  UserQA
}

type Query {
  user(userID: String!, midName: String): User!
  allCalls: [Call!]!
}

type Subscription {
  newUser: User!
}
```
</details>
<details>
<summary>GraphQL query:</summary>

```
subscription NewUserSub {
  newUser {
    firstName
    lastName
    userType
  }
}
```
</details>

**Comment by vasilich6107** [comment]
Let me check...

**Comment by vasilich6107** [comment]
Use latest atremis beta v6.12.3-beta.1

**Comment by vasilich6107** [comment]
created a test from your code to confirm that everything works
https://github.com/comigor/artemis/pull/219

**Comment by vasilich6107** [comment]
Hi @oofp 
Any news?

**Comment by vasilich6107** [comment]
Closing the issue for now. If you have more questions feel free to reopen

**Comment by aloisdeniel** [comment]
I have the same issue. :'(

**Comment by vasilich6107** [comment]
@aloisdeniel please create a separate issue.
Before that be sure that you use latest beta version of Artemis
