### ISSUE TITLE
Update gql dependencies

### ISSUE THREAD

**Issue by ram231** [comigor/artemis#217]
Hi, I'm getting an error when updating `graphql` package alongside with artemis.
```sh
Because artemis 6.12.3-beta.1 depends on gql_http_link ^0.2.9 and no versions of artemis match >6.12.3-beta.1 <7.0.0, artemis ^6.12.3-beta.1 requires gql_http_link ^0.2.9.
```
I might submit a PR. Thanks!

**Comment by ram231** [comment]
@vasilich6107 do you also update dependencies inside the example folder?

**Comment by vasilich6107** [comment]
you can also use `dependacy_overrides`

**Comment by vasilich6107** [comment]
Updated deps in #221
