### ISSUE TITLE
Cannot Handle BadRequestException or any other exceptions thrown from server

### ISSUE THREAD

**Issue by codiyer** [comigor/artemis#220]
Hi, 
I am using NestJS on the server side with Apollo for graphql. There are cases where the server throws Forbidden or BadRequestException and I need to handle the exception on the app.

The response that we receive in such cases are something as follow:
```json
{
  "errors": [
    {
      "message": {
        "statusCode": 400,
        "error": "Bad Request",
        "message": "Trial"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "response": {
            "statusCode": 400,
            "error": "Bad Request",
            "message": "Trial"
          },
          "status": 400,
          "message": {
            "statusCode": 400,
            "error": "Bad Request",
            "message": "Trial"
          },
          "stacktrace": [
            "Error: [object Object]",
            "    at UserResolver.users (/Users/sabrish/Documents/Ocufox/Projects/Vpledge/code/server/.webpack/service/apps/api/client/src/index.js:8188:15)",
            "    at /Users/sabrish/Documents/Ocufox/Projects/Vpledge/code/server/node_modules/@nestjs/core/helpers/external-context-creator.js:70:29",
            "    at InterceptorsConsumer.intercept (/Users/sabrish/Documents/Ocufox/Projects/Vpledge/code/server/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:10:20)",
            "    at target (/Users/sabrish/Documents/Ocufox/Projects/Vpledge/code/server/node_modules/@nestjs/core/helpers/external-context-creator.js:75:60)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at /Users/sabrish/Documents/Ocufox/Projects/Vpledge/code/server/node_modules/@nestjs/core/helpers/external-proxy.js:8:24"
          ]
        }
      }
    }
  ],
  "data": null
}
```

However, in such cases artemis client simply throws ResponseFormatException and we are receiving just a single line as follows:
`type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String' in type cast`

Is there any way of getting the the objects inside errors array or atleast getting hold of the actual response body?

I am using artemis: 6.12.3-beta.1 with flutter 1.20.4.

**Comment by codiyer** [comment]
Hi,
We found out that the issue was from NestJs graphql module itself and was resolved in the newer versions of the graphql module. 
This issue got resolved after upgrading the server side dependencies. 

It would however be great if we can somehow have the actual response object via the ResponseFormatException instance

**Comment by vasilich6107** [comment]
Hi.
Use graphq_flutter package.
I do not think we will have time to support client
https://medium.com/@v.ditsyak/ultimate-toolchain-to-work-with-graphql-in-flutter-13aef79c6484
