### ISSUE TITLE
Can't have artemis generate class correctly.

### ISSUE THREAD

**Issue by Zony-Zhao** [comigor/artemis#225]
Research on this lib for a long while, which seems to be the largest active dart graphql generator but didn't get any progress.
## What I've done
I followed this [Ultimate graphql tool-chain on Medium](https://medium.com/@v.ditsyak/ultimate-toolchain-to-work-with-graphql-in-flutter-13aef79c6484). 
And when I run the generate command. 0 output files.
### cmd output
![image](https://user-images.githubusercontent.com/50739849/95014929-d25db500-067c-11eb-8d52-2638a877546e.png)
### build.ymal
![image](https://user-images.githubusercontent.com/50739849/95014940-e99ca280-067c-11eb-9d97-edd8710e377f.png)
### schema
![image](https://user-images.githubusercontent.com/50739849/95014944-f620fb00-067c-11eb-9995-52912d1c0591.png)
### query file
![image](https://user-images.githubusercontent.com/50739849/95014956-ff11cc80-067c-11eb-8555-828824b1ce23.png)
### pubspec.yaml
![image](https://user-images.githubusercontent.com/50739849/95014978-181a7d80-067d-11eb-9d40-0cdfcc82b499.png)
## What I want
1. generate model class correctly.
2. not sure whether artemis generate class for QueryInput types? I have relatively complex input type in my project, it's very important.

**Comment by vasilich6107** [comment]
Hi. Please use the latest Artemis beta.
If it does not help fill the issue with text not the screenshots. The main goal is to have quick examples of data to copy.

**Comment by vasilich6107** [comment]
The latest beta is 6.x.x
You are using pretty old version 2.x.x

**Comment by vasilich6107** [comment]
@Zony-Zhao any updates?

**Comment by vasilich6107** [comment]
Closing this issue due to the lack of feedback.
