### ISSUE TITLE
Feature request: Annotate `unknownEnumValue` on lists

### ISSUE THREAD

**Issue by budde377** [comigor/artemis#246]
Thanks for a great project. I've recently encountered an argument error with parsing enum values in lists, e.g.

```graphql
enum E {
  V1
}

type T {
  enum: E!
  listOfEnums: [E!]!
}

schema {
  query: T
}

fragment F on T {
    listOfEnums
    enum
}

query Q {
    ...F
}

```

Here the above will generate the code

```dart
mixin FMixin {
  List<E> listOfEnums;
  @JsonKey(name: 'enum', unknownEnumValue: E.artemisUnknown)
  E kw$enum;
}

...

enum E {
  @JsonValue('V1')
  v1,
  @JsonValue('ARTEMIS_UNKNOWN')
  artemisUnknown,
}
```

I might be out of the loop, but it looks to me that this was removed in https://github.com/comigor/artemis/pull/85, since then it seems to be supported by `json_serializable` (https://github.com/google/json_serializable.dart/issues/585), and it does indeed seem to work locally. 

Can this functionality be added back? I.e. so the generated code will be

```dart
mixin FMixin {
  @JsonKey(name: 'listOfEnums', unknownEnumValue: E.artemisUnknown) 
 List<E> listOfEnums;
  @JsonKey(name: 'enum', unknownEnumValue: E.artemisUnknown)
  E kw$enum;
}```

**Comment by comigor** [comment]
Hello @budde377!
Yeah, given this was fixed on json_serializable in August, it should be reverted here as well.
Could you open a PR with this fix? I'd greatly appreciate that!

**Comment by budde377** [comment]
Sure, I'll give it a go!

**Comment by vasilich6107** [comment]
Hi @budde377
Could you check if the latest release works for you?

**Comment by budde377** [comment]
@vasilich6107 Just checked, the latest release correctly annotated the field! Thanks!
