### ISSUE TITLE
Artemis should error out with multiple queries per file in queries_glob

### ISSUE THREAD

**Issue by louisrli** [comigor/artemis#251]
**Before reporting a bug, please test the beta branch!**

## Bug description
The files in queries_glob can't have more than one op per file as mentioned in this comment https://github.com/comigor/artemis/issues/174#issuecomment-642204509

This issue is for an error to occur when running the tool if such a case is detected (since the op's not going to end up working anyway).

As further background for anyone else who stumbles here (just to explain):
If you include multiple queries in a file, you get a huge query sent along (and the generated code's `document` property also contains everything).

![image](https://user-images.githubusercontent.com/1303401/104807090-e795c400-57d3-11eb-84f8-035a0a8fa8f1.png)

I filed #250 as a PR to update the README.md at least to make this more clear (rather than having to look through the issues).

## Specs
Artemis version: 6.17.3

**Comment by vasilich6107** [comment]
Hi @louisrli 
While awaiting for release could you instal the version from git dependency and check if it solves your issue.

**Comment by vasilich6107** [comment]
The fix will be available in 6.18.3

**Comment by vasilich6107** [comment]
Hi @louisrli 
Did you have time to check the fix?

**Comment by vasilich6107** [comment]
Hi, @louisrli 
Any updates?

**Comment by louisrli** [comment]
I think it's fixed. Sorry for the slow response. The document node seems to be correctly split now. Thanks!
