### ISSUE TITLE
JsonSerializable responses and inputs

### ISSUE THREAD

**Issue by oakesja** [comigor/artemis#257]
The app that I am working on persists mutations when offline to run them later. To do so we use a background isolate to process in the background. When sending messages back in forth between the main isolate and a background isolate, the message must be serializable. 

Would it be possible to make the auto-generated types for responses extend JsonSerializable?

This would make it much easier to pass response objects back and forth from isolates.

**Comment by vasilich6107** [comment]
Do you mean this one?

https://github.com/comigor/artemis/blob/master/test/query_generator/query_generator_test.dart#L201

**Comment by vasilich6107** [comment]
Could you add several lines of code in “actual result” vs “expected result” for all the places where you need “extends JsonSerialisable” so it will be easier for us to “point and shoot” with fixes.

**Comment by vasilich6107** [comment]
Add this `feat/extend-json-serializable` branch as your dependency and tell us if it fits your needs

**Comment by vasilich6107** [comment]
Ha ha)
I missed your PR)

**Comment by vasilich6107** [comment]
Wait for `6.20.1-beta.1` release. It will take several minutes to run the pipeline.

**Comment by vasilich6107** [comment]
Hi @oakesja 
Did you test the latest beta?

**Comment by oakesja** [comment]
@vasilich6107 yep, everything is working as expected
