### ISSUE TITLE
Camel case query names are converted to snake_case on operationName

### ISSUE THREAD

**Issue by danilolr** [comigor/artemis#26]
A query like this :

```
query RygappGeral {
  versao
}
```

generates a file with :

final String operationName = 'rygapp_geral';

As the names are not equals it gives a runtime erro of : 

Unknown operation named "rygapp_geral"

If I named my query rygapp_geral it works fine.

**Comment by BioApfelsaft** [comment]
#45

**Comment by comigor** [comment]
Fixed on https://github.com/comigor/artemis/pull/45
