### ISSUE TITLE
[Feature request] Allow stopping subscriptions

### ISSUE THREAD

**Issue by euriasb** [comigor/artemis#260]
Add a way to stop a subscription.

Right now once you start a subscription you either have to keep it open forever or close the client entirely which is not ideal, it would be best if you didn't have to open a socket for each subscription in order to have control of when to stop it.

I dug into the code for `WebSocketLink` and I can see that it doesn't offer support to do this either, so it looks like that project would need to add support for it as well.

I would be happy to contribute to both projects to achieve this if necessary since it is a high priority for my project.

**Comment by comigor** [comment]
Hey @euriasb, how are you doing?

I personally don't use subscriptions on my production apps, but this seems important. ArtemisClient is not supposed to be a fully featured client (we leverage `Link`'s for that), but it absolutely can be enhanced if necessary (let's say, with an `abort()` method).

Please ping me again if you need any help!

**Comment by BreSmit521** [comment]
Any word on the progress of this?

**Comment by euriasb** [comment]
I submitted a PR to the gql project to allow stopping subscriptions https://github.com/gql-dart/gql/pull/205, I have one ready for Artemis as well, where I'm simply propagating the response context from the gql response, that way you can get the request ID and stop a subscription directly on the WebSocketLink.
I'm waiting to get comments from the gql project, once I do I'll submit my PR here as well.

**Comment by euriasb** [comment]
I opened https://github.com/comigor/artemis/pull/278 since I realized it doesn't really depend on the change on gql.

**Comment by euriasb** [comment]
I spoke with one of the contributors of gql, and it turns out that it is already possible to stop a subscription on their end, you just need to cancel the subscription to the stream, so basically this snippet does the trick:

```
final subscription = <your subscription>
final stream = client.stream(subscription);
final sub = stream.listen(...);
// do your work
sub.cancel();
```

The `WebSocketLink` is still usable afterwards, I just tried it in my project and it works perfectly.
