### ISSUE TITLE
[Question] Are empty types supported with scalar_mapping ?

### ISSUE THREAD

**Issue by MattisBrizard** [comigor/artemis#266]
Hi,

I have a question about the support of empty types with artemis scalar_mapping:
ex:
```
type Area {
  title: I18n
}
"""
The `I18n` type represents textual data, represented as UTF-8
character sequences. It represents the translated text of a multilanguage field.
"""
type I18n
```

If we have the above gql scheme, and the following scalar_mapping:
```
scalar_mapping:
            - graphql_type: I18n
              dart_type: String
```

Will it works ?

I'm actually trying to figure out why we have an issue in artemis generated types. 
One of my clue is the handling of empty types.

Mattis

**Comment by vasilich6107** [comment]
Hi. Technically your sample should work.
If you have issues please fill the issue template with all data required to reproduce the bug

**Comment by MattisBrizard** [comment]
Hi.
Thanks, I close this issue for now.
