### ISSUE TITLE
[Question] About your codebase setup?

### ISSUE THREAD

**Issue by emme1444** [comigor/artemis#277]
Hey @comigor! 

Love your work on this package. Used it for some time now. However, among other things, it inspired me to write my own generator. I quickly took a look at your codebase to find some tips and tricks and quickly discovered a way better solution than I originally proposed to myself regarding serializing the _builder options_. `json_serializable`, of course!

I was just wondering about how you manage to use `json_serializable` while declaring a builder at the same time? I see some sneaky `.g2.dart` stuff, might that have to do with something? I've just been in a discussion over at dart-lang/build#3057 discovering that the build system in use can't handle this sort of setup. My work-around at the moment is to comment out the "builder definition" for my builder/generator in my `build.yaml` file of the generator package, run `build_runner` and then uncomment it again. 

Do you have a similair issue? And if so, how do you work around it? If not, could you suggest something for me to do in order to alleviate the problem. Or am I simply missing something here?

Hope this doesn't take too much of your time. I didn't really know how else to reach you, so an issue it is.

Thanks!

**Comment by comigor** [comment]
Hey @emme1444, sorry for taking that long to reply!

Actually, I've bumped into this issue right when I've started Artemis, and that's exactly why there's the `.g2.dart`: that's me changing the extension to avoid `build_runner` being triggered for this project and failing.

What I do is a terrible manual job: everytime I need to change the generated file, I revert it back to `.g.dart`, comment `build.yaml` of Artemis, run `build_runner` and change it back to `.g2.dart` 😢 

Sorry if this is disappointing, but I haven't found any other way past this.

**Comment by emme1444** [comment]
No worries! Thanks for your response. Better late than never!

I see, so nothing that I hadn't expected. Oh well. That's the reality as it seems. We will all keep using this mess of a workaround then. Thanks for your insight. Have a great day!
