### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by teknolojia** [comigor/artemis#280]
**Before reporting a bug, please test the beta branch!**

## Bug description
Please describe what happened wrong and the expected behaviour/output.
I am tying to update my app to use latest version of dio but I get error every time

> Because no versions of http match >0.12.2 <0.13.0 and http 0.12.2 depends on http_parser >=0.0.1 <4.0.0, http ^0.12.2 requires http_parser >=0.0.1 <4.0.0.
> And because dio >=4.0.0-beta1 depends on http_parser ^4.0.0, http ^0.12.2 is incompatible with dio >=4.0.0-beta1.
> So, because graph depends on both dio ^4.0.0 and http ^0.12.2, version solving failed.
> pub get failed (1; So, because graph depends on both dio ^4.0.0 and http ^0.12.2, version solving failed.)

```
  artemis: ^7.0.0-beta.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
```
can we update http?
## Specs
Artemis version: [e.g. 6.0.3-beta.1]
<details>
<summary>build.yaml:</summary>
  
```yaml
# Please paste your `build.yaml` file
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
# Please paste the output of
$ flutter pub run build_runner build --verbose
#or
$ pub run build_runner build --verbose
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
# If possible, please paste your GraphQL schema file,
# or a minimum reproducible schema of the bug.
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
# If possible, please paste your GraphQL query file,
# or a minimum reproducible query of the bug.
```
</details>

**Comment by vasilich6107** [comment]
PR with nnbd support and packages upgrade is in review now.

**Comment by comigor** [comment]
@teknolojia We've just merged https://github.com/comigor/artemis/pull/283 with NNBD support for Artemis.
I'm closing this but feel free to open another issue, if applicable, after testing the new version `7.0.0-beta.2`.
