### ISSUE TITLE
nnbd - code_builder and build_config

### ISSUE THREAD

**Issue by jlnrrg** [comigor/artemis#298]
The `code_builder` and `build_config` library finally made the cut to nnbd.
Please publish a new beta version that includes this new version, 
as the [auto_route library](https://github.com/Milad-Akarie/auto_route_library/issues/486) now requires `code_builder: ^4.0.0`
and [freezed](https://pub.dev/packages/freezed/changelog#01413) requires `build_config: ^1.0.0`.

**Comment by jlnrrg** [comment]
The bug label was my mistake, sry

**Comment by comigor** [comment]
Hello there, we've already been using those latest versions on beta branch for a while:  https://github.com/comigor/artemis/blob/beta/pubspec.yaml#L11-L12

**Comment by jlnrrg** [comment]
my bad

**Comment by comigor** [comment]
no problem, thank you!
