### ISSUE TITLE
GraphQL interfaces

### ISSUE THREAD

**Issue by amadeu01** [comigor/artemis#30]
In my schema, I have something like:

```
type MyType implements Blah & PublicBlahInterface & BlahSharedProperties { ... }
```

And the generated code got something like

```dart
class MyQuery extends MyTypes
    with EquatableMixin
    implements Blah, PublicBlahInterface, BlahSharedProperties {
```

However `Blah, PublicBlahInterface, BlahSharedProperties` never got created by the builder.

**Comment by amadeu01** [comment]
I don't know why, but when I used separated file for each query, it worked 

Something like that 
https://github.com/comigor/artemis/blob/ce09046f67f2e27d4365768e3fe7c27fc5369206/example/pokemon/build.yaml#L8-L16

one output per query, instead of using one output for every `**.query` file

**Comment by comigor** [comment]
Hey @amadeu01!

That's actually the way it's supposed to work as-of-now (since `v1.0.0`: to have an output for each query, or for mutiple queries that don't share the same entities), or else you'll got an exception if two or more queries use the same types. As I've said on https://github.com/comigor/artemis/issues/27, I'm thinking in a way of changing this behavior, to be able to use `queries_glob` nicely again.

However, if your queries don't share the same types, this is not the intended behavior. Could you create a sample repository that reproduces this error?

**Comment by smkhalsa** [comment]
@comigor I have the same issue as @amadeu01: my interface types aren't generated.

I created a [minimum reproduction repo](https://github.com/smkhalsa/artemis_demo).

As you can see, the `AudioContext` and `SearchResult` interface classes were not created. For your reference, here is my schema.

```
interface SearchResult {
  id: ID!
  name: String!
}

interface AudioContext {
  id: ID!
  name: String!
}

input ImageUrlInput {
  height: Int
  width: Int
  watermark: Boolean
}

type Song implements SearchResult {
  id: ID!
  name: String!
  imageName: String
  imageUrl(options: ImageUrlInput): String
  fileName: String!
  fileUrl: String!
}

type FeaturedPlaylist implements AudioContext & SearchResult {
  id: ID!
  name: String!
  songs: [Song!]!
  songCount: Int!
  imageName: String!
  imageUrl(options: ImageUrlInput): String!
}
```

Also, I get the following warnings when building. For some reason artemis is looking for an `imageUrl` property on `SearchResult` and `AudioContext`.

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 533ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 22.0s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 868ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[WARNING] artemis:artemis on lib/$lib$:
Could not find property "imageUrl" of class "AudioContext". Moving on...
[WARNING] artemis:artemis on lib/$lib$:
Could not find property "imageUrl" of class "AudioContext". Moving on...
[WARNING] artemis:artemis on lib/$lib$:
Could not find property "imageUrl" of class "SearchResult". Moving on...
[WARNING] artemis:artemis on lib/$lib$:
Could not find property "imageUrl" of class "SearchResult". Moving on...
[INFO] Generating SDK summary...
[INFO] 7.3s elapsed, 1/3 actions completed.
[INFO] Generating SDK summary completed, took 7.0s

[INFO] 8.5s elapsed, 1/3 actions completed.
[INFO] 14.4s elapsed, 2/3 actions completed.
[INFO] Running build completed, took 15.2s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 48ms

[INFO] Succeeded after 15.3s with 3 outputs (8 actions)
```

**Comment by comigor** [comment]
Nice, I'll take a look based on this reproduction!

**Comment by smkhalsa** [comment]
@comigor were you able to take a look at this?

**Comment by comigor** [comment]
Sorry, I didn't have the time yet 😞

**Comment by comigor** [comment]
I've opened a PR to fix your case, @smkhalsa: https://github.com/comigor/artemis/pull/46
Though I'm not sure that's the same problem as @amadeu01

**Comment by comigor** [comment]
Feel free to reopen this as needed, as a fix to the reproducible bug is shipped on https://pub.dev/packages/artemis/versions/2.0.7
