### ISSUE TITLE
GraphQL Mutation widget and new Artemis constructor null safety issue

### ISSUE THREAD

**Issue by michael-woolsey** [comigor/artemis#305]
## Bug description
The challenge I am encountering is with the new null safety, our mutation objects now require variables.  Which at first glance is the way it should be, however when used in combination with the `graphql_flutter` package's Mutation widget it illustrates a challenge.

The challenge is that I need the mutations `documentNode` for setting up the widget as seen in `options: MutationOptions(document: _mutation.document),`  from the sample code below, which I previously acquired like `final _mutation = UpdateUserNameMutation();`.

However, when you first create the mutation object, you wouldn't have the new values that you want to update as you have only just displayed the screen before the user could change anything.

I realize I could likely just pass in blank strings or default values to get the mutation object created, but that doesn't 'feel' like the correct way of handling this situation.  

Truth be told, I have worked around the problem by not using Mutation widgets at all, but I wanted to share what I encountered in case it's something you feel that needs to be addressed.

## Specs
Artemis version: ^7.0.0-beta.10
  
Sample code:
```js
mutation UpdateUserName($id: UUID!, $name: String!) {
  updateUser(input: {id: $id, patch: {name: $name}}) {
    user {
      __typename
      id
      name
    }
  }
}
```
```js
class ExampleTextField extends StatefulWidget {
  const ExampleTextField({Key key}) : super(key: key);

  @override
  _ExampleTextFieldState createState() => _ExampleTextFieldState();
}

class _ExampleTextFieldState extends State<ExampleTextField> {
  final _query = UserNameQuery();
  final _mutation = UpdateUserNameMutation();

  var _id = '';
  var _name = '';

  @override
  Widget build(BuildContext context) {
    return Query(
      options: QueryOptions(document: _query.document),
      builder: (QueryResult result, {Refetch? refetch, FetchMore? fetchMore}) {
        if (result.isLoading || result.data == null || _query.parse(result.data).currentUser == null) {
          return Container(color: Theme.of(context).backgroundColor);
        }

        _id = _query.parse(result.data!).currentUser!.id;
        _name = _query.parse(result.data!).currentUser!.name;

        return Mutation(
          options: MutationOptions(document: _mutation.document),
          builder: (RunMutation? runMutation, QueryResult? result) {
            return Focus(
              onFocusChange: (hasFocus) {
                if (!hasFocus) {
                  final mutation =
                      UpdateUserNameMutation(variables: UpdateUserNameArguments(id: _id, name: _name.trim()));
                  runMutation!(mutation.getVariablesMap());
                }
              },
              child: TextFormField(
                textCapitalization: TextCapitalization.sentences,
                decoration: const InputDecoration(
                  floatingLabelBehavior: FloatingLabelBehavior.always,
                  labelText: 'Name',
                ),
                initialValue: _name,
                onChanged: (String value) => _name = value,
              ),
            );
          },
        );
      },
    );
  }
}
```
Hopefully this makes sense!

**Comment by vasilich6107** [comment]
Check the generated sources
each document now in separate variable `CHECKOUT_BY_ID_QUERY_DOCUMENT`

**Comment by michael-woolsey** [comment]
Oh okay, I see now... I would use it like this:
```js
options: QueryOptions(document: USER_NAME_QUERY_DOCUMENT),
```

Great, that's exactly what I needed to know, thanks a bunch @vasilich6107! :)
