### ISSUE TITLE
[Question] Custom types along with generated ones

### ISSUE THREAD

**Issue by fpabl0** [comigor/artemis#306]
Hello, is there a way to tell Artemis to use specific already defined types instead of generating them?
Basically, I want to define my main models myself but let Artemis to autogenerate other code like inputs, payloads, edges, etc. Is this possible? Thanks :)

**Comment by vasilich6107** [comment]
Could you describe what problem are you solving with your custom models?
Current Artemis does not support usage of external types.

**Comment by fpabl0** [comment]
I just wanted to avoid having to reference my core models like "SearchRepositories$Query$SearchResultItemConnection$SearchResultItem" (it is too long). If I can define `SearchResultItem` myself, then I can avoid it.

**Comment by vasilich6107** [comment]
Extract all your objects into Fragments to have shorter names
See this issue https://github.com/comigor/artemis/issues/230

**Comment by fpabl0** [comment]
Got it, thanks :). The only disadvantage of using Mixins is that I need to manually cast the result with `as`:
```dart
    final parsed = GetPokemon$Query.fromJson(resp.data).resp;
    if (parsed is PokemonFragmentMixin) {
      final r = parsed as PokemonFragmentMixin;
      return Pokemon(name: r.name, number: r.number);
    }
```
One more doubt (sorry to ask here), queries need to be defined in separated files? Because when I want to define two queries in a file, I got two errors:
```
Fragment "errorFragment" is never used.
There can be only one fragment named "pokemonFragment".
```

**Comment by vasilich6107** [comment]
You do not need a separate cast - dart is smart enough to refine types under `if` clause

Check this sample

```
abstract class A {}

class B extends A {
  final String test;

  B(this.test);
}

class C extends A {
  final String test123;

  C(this.test123);
}

abcd(A aClass) {
  if (aClass is B) {
    print(aClass.test);
  }

  if (aClass is C) {
    print(aClass.test123);
  }
}
```

**Comment by vasilich6107** [comment]
For the error - create and fill in another issue

**Comment by fpabl0** [comment]
> You do not need a separate cast - dart is smart enough to refine types under if clause

@vasilich6107 That is only true for `classes` not for `mixins`, take a look:

```dart
mixin PokemonFragmentMixin {
  String? name;
  String? number;
}

mixin ErrorFragmentMixin {
  String? message;
}

abstract class Result {}

class Pokemon extends Result with PokemonFragmentMixin {
  Pokemon(String name) {
    this.name = name;
  }
}

class Error extends Result with ErrorFragmentMixin {
  Error();
}

void main() async {
  Result r = Pokemon("Charmander");
  if (r is PokemonFragmentMixin) {
    // print(r.name); // THIS DOES NOT WORK
  }
  if(r is Pokemon) {
    print(r.name);
  }
}
```

**Comment by vasilich6107** [comment]
One small fix and everthing works fine - check this

```dart
mixin PokemonFragmentMixin {
  String? name;
  String? number;
}

mixin ErrorFragmentMixin {
  String? message;
}

abstract class Result {}

class Pokemon extends Result with PokemonFragmentMixin {
  Pokemon(String name) {
    this.name = name;
  }
}

class Error extends Result with ErrorFragmentMixin {
  Error();
}

void main() async {
  final r = Pokemon("Charmander");
  if (r is PokemonFragmentMixin) {
    print(r.name);
  }
  if(r is Pokemon) {
    print(r.name);
  }
}
```

**Comment by vasilich6107** [comment]
If you define non `final` variable dart static analyzer could not be sure that this variable was not modified somewhere in the middle.

**Comment by fpabl0** [comment]
> One small fix and everthing works fine - check this

That works because you are instantiating `Pokemon` directly (it already has `name` and `number` fields so the `is` keyword is not doing any magic). The problem comes when you have unions (that is why I use `Result`), then you have the problem I mentioned above.

> If you define non final variable dart static analyzer could not be sure that this variable was not modified somewhere in the middle.

I am not sure how is that statement related to this. I can declare it as `final` and the problem will be still there because the type will not change (with/without `final`).

```dart
void main() async {
  final Result r = Pokemon("Charmander");
  if (r is PokemonFragmentMixin) {
    // print(r.name); // THIS DOES NOT WORK
  }
  if(r is Pokemon) {
    print(r.name);
  }
}
```

**Comment by vasilich6107** [comment]
`final Result r = Pokemon("Charmander");` => `final r = Pokemon("Charmander");` remove type declaration from statement
And everything will work fine

**Comment by fpabl0** [comment]
With this line `final Result r = Pokemon("Charmander");` I am just simulating what I will get from the server. This is the definition in graphql:
```gql
union Result = Pokemon | Error

type Query {
    pokemon(name: String!): Result!
}
```
So I will receive a `Result` value that I need to check whether it is a `Pokemon` or it is an `Error`, that is what I want to illustrate with that line.

**Comment by vasilich6107** [comment]
What's happening behind the scene does not matter a lot.
We are discussing the `redundant type casting`

I'm showing you examples to illustrate the way to avoid them.
If examples is not enough - show me your real code with error

**Comment by fpabl0** [comment]
I have already given to you my testing code above:

**schema:**
```gql
type Pokemon {
  number: String
  name: String
}
type Error {
  code: Int!
  message: String!
}
union PokemonResult = Pokemon | Error
type Query {
  pokemon(name: String!): PokemonResult!
}
```

**queries:**
```gql
fragment pokemonFragment on Pokemon {
  number
  name
}

fragment errorFragment on Error {
  code
  message
}

query getPokemon($name: String!) {
  resp: pokemon(name: $name) {
    __typename
    ... on Pokemon {
      ...pokemonFragment
    }
    ... on Error {
      ...errorFragment
    }
  }
}
```
**code:**
```dart
    final parsed = GetPokemon$Query.fromJson(resp.data).resp; // 👈 this is of type GetPokemon$Query...PokemonResult
    if (parsed is PokemonFragmentMixin) {
      final r = parsed as PokemonFragmentMixin;
      return Pokemon(name: r.name, number: r.number);
    }
    if (parsed is ErrorFragmentMixin) {
      final r = parsed as ErrorFragmentMixin;
      throw r.message;
    }
```
Hope this time, I am explaining better what I mean. Sorry for any inconvenience.

**Comment by vasilich6107** [comment]
I've found sample of Unions in my old project and it is definitely refuses to recognise Mixins

**Comment by vasilich6107** [comment]
I have no idea why this happening for now)
I;ll try to think about it

**Comment by fpabl0** [comment]
Thanks :), and sorry for the inconveniences.

**Comment by vasilich6107** [comment]
Strange things  - this code works fine

```dart
class A {}

mixin DataMixin {
  String? name;
}

class Data extends A with DataMixin {}

mixin SpecificErrorMixin on SpecificError {
  String? code;
}

class SpecificError extends A {}

mixin ErrorMixin {
  String? message;
}

class Error extends A with ErrorMixin {}

A abcd() {
  var test = false;
  if (test) {
    return Data();
  }

  if (test) {
    return SpecificError();
  }

  return Error();
}

void main() {
  final data = abcd();

  if (data is SpecificErrorMixin) {
    print(data.code);
  }
}
```

**Comment by vasilich6107** [comment]
and this - not

```dart
class A {}

mixin DataMixin {
  String? name;
}

class Data extends A with DataMixin {}

mixin SpecificErrorMixin {
  String? code;
}

class SpecificError extends A with SpecificErrorMixin {}

mixin ErrorMixin {
  String? message;
}

class Error extends A with ErrorMixin {}

A abcd() {
  var test = false;
  if (test) {
    return Data();
  }

  if (test) {
    return SpecificError();
  }

  return Error();
}

void main() {
  final data = abcd();

  if (data is SpecificErrorMixin) {
    print(data.code);
  }
}

```

**Comment by vasilich6107** [comment]
The only difference is how we define mixin with `with` or `on`

**Comment by fpabl0** [comment]
Hmm, maybe Dart can only cast directly to Mixins when their definitions declare specifically in what kind of types it is going to be used?
