### ISSUE TITLE
Connections and Unions

### ISSUE THREAD

**Issue by jhattwich** [comigor/artemis#31]
Hey there! First of all thanks for this package, it really helps us to improve our development process! I have some troubles building unions and connections with unions. 

I have the following gql queries: 

```
query Search($searchTerm, $filters, $first, $last, and more...) {
  edges {
    node {
      .. on Product {
        id
      }
      .. on User {
        id
      }
    }
  }
}
```
or 

```
query CurrentViewer($id, $favorites_first, and more..) {
  node(id: $id) {
    id
    favorites(first: $favorites_first) {
      edges {
        node {
          .. on Location {
            id
          }
          .. on Category {
            id
          }
        }
      }
    } 
  }
}
```

In both cases the type `Node` has no `props` e.g.:

```dart
--- SNIP ---
@JsonSerializable(explicitToJson: true)
class Searchables with EquatableMixin {
  Searchables();

  factory Searchables.fromJson(Map<String, dynamic> json) =>
      _$SearchablesFromJson(json);

  @override
  List<Object> get props => []; # empty props 
  Map<String, dynamic> toJson() => _$SearchablesToJson(this);
}
--- SNIP ---
```

Expectation is:

```
--- SNIP ---
@JsonSerializable(explicitToJson: true)
class Node with EquatableMixin {
  Node();

  factory Node.fromJson(Map<String, dynamic> json) {
    switch (json['__typename']) {
      case 'Category':
        return Category.fromJson(json);
      case 'Location':
        return Location.fromJson(json);
      default:
    }
    return _$NodeFromJson(json);
  }
}
--- SNIP ---
```

**Comment by comigor** [comment]
Hello @0x6a6f74726f!
Are you setting `resolve_type_field` on `schema_mapping` configuration to `__typename`?
Is this an union type?
Could you share the GraphQL schema or create a minimal reproducible repository with this issue?
Thanks!

**Comment by michael-golfi** [comment]
Hi @comigor - First off, thanks for all the great work! :)

Is typename only generated for interfaces and unions? I'm using typename for caching on every object and wondering if there's a way to add it when it's specified in the queries?

**Comment by 0x6a6f74726f** [comment]
@comigor yes we set the `resolve_type_field` according to our schema. If you need more stuff, i am happy to support!

**Comment by comigor** [comment]
@0x6a6f74726f Cool! I'll take a look at it when I got some time.

@michael-golfi Hey there! Thank you! For now we only generate typename for interfaces and union types "instances". We also drop any other field that starts with `__` to have its code generated. Are you using typename differently? Does it agree with GraphQL protocol? Maybe we think in a way of whitelisting those fields if necessary.

**Comment by michael-golfi** [comment]
I'm not sure that it's necessarily part of the protocol but I'm running queries similar to the following:

```graphql
query Me {
    viewer {
        __typename
        id
        firstName
        lastName
    }
}
```

But the class only generates fields for id, firstName and lastName. If the query requests __typename, should it appear in the class as well?

**Comment by comigor** [comment]
No. It's currently, on purpose, filtering any field that starts with `__`.

That's why I've asked what's the use case for this, so maybe we can remove this filter.

**Comment by michael-golfi** [comment]
That would be great! 

I use __typename/id as a key for client side caching.

**Comment by comigor** [comment]
@michael-golfi I've create a new issue to not filter those fields, let's keep this one to the connection problem.

https://github.com/comigor/artemis/issues/41

**Comment by comigor** [comment]
Hey @jhattwich,

I've recently release 4.0.0 and this was probably fixed among other things! (And with an working example of GitHub)

Feel free to reopen thiss issue if the error still happen after bumping.
