### ISSUE TITLE
Request: Option to remove variables field from generated code

### ISSUE THREAD

**Issue by kateile** [comigor/artemis#314]
This not a bug actually just a feature request.
I am using artemis `6.20.1-beta.2` with graphql-flutter and they work really well together. But recently I was trying to update all of dependencies to latest releases and with artemis `^7.0.0-beta.3` most of my codes would break by requiring `variables` field in every Query/Mutation.

I know having `variables` there plays a crucial role in ArtemisClient but since we are not planning on switching from graphql-flutter to ArtemisClient soon. I just wish how we pass variables remains the same.

So I am just requesting for an option to turn it off during build. So add option in build.yaml would be better

Code examples

```dart
  Future<QueryResult> fetchAccount(AccountArguments args) {
    final _options = QueryOptions(
      document: AccountQuery().document, //Warning: The parameter 'variables' is required
      variables: args.toJson(), //I prefer to pass it here like this
    );

    return client.query(_options);
  }
```

```dart
class AccountQuery extends GraphQLQuery<Account$Query, AccountArguments> {
  AccountQuery({required this.variables}); //This should be just  AccountQuery();

  @override
  final DocumentNode document = ACCOUNT_QUERY_DOCUMENT;

  @override
  final String operationName = 'account';

  @override
  final AccountArguments variables;

  @override
  List<Object?> get props => [document, operationName, variables];
  @override
  Account$Query parse(Map<String, dynamic> json) =>
      Account$Query.fromJson(json);
}
```

I know there are few solutions to this
1. Write code as
```dart
  Future<QueryResult> fetchAccount(AccountArguments args) {
    final query = AccountQuery(variables: args); //I DON'T WANT THIS
    final _options = QueryOptions(
      document: query.document,
      variables: query.variables.toJson(),
    );

    return client.query(_options);
  }
```

2. Stay on v6 (This is my preferred choice). Can be we update its dependencies there too many conflicts with graphql packages

**Comment by vasilich6107** [comment]
Check this issue https://github.com/comigor/artemis/issues/305

**Comment by kateile** [comment]
@vasilich6107  That helped. I will use [separate variable](https://github.com/comigor/artemis/issues/305#issuecomment-833366527) in place of `document`
