### ISSUE TITLE
Reordered schema.graphql.dart on Github actions

### ISSUE THREAD

**Issue by Tahmeed27** [comigor/artemis#323]
## Bug description
So when I run the code generation on my own terminal I don't get any diff from the last time I used it. However, I set up a github action to run the same flutter build_runner command on my github actions and I'm getting a diff in the schema.graphql.dart and schema.graphql.dart.g files. When I inspected the diff, it seems that the files look the same and still works but then for some reason the order of the generated code schemas gets shuffled around causing a diff. Is there any reason why the environment produced from running the code using github actions would give different output to running the code from my local version? Or is there anyway to force the codegen to do them in the same order? They use the same version of flutter if that helps. I'm not sure if specs would help in this case so I'll update the post based on a reply

## Specs
Artemis version: [7.0.0-beta.131]
<details>
<summary>build.yaml:</summary>
  
```yaml
# Please paste your `build.yaml` file
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
# Please paste the output of
$ flutter pub run build_runner build --verbose
#or
$ pub run build_runner build --verbose
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
# If possible, please paste your GraphQL schema file,
# or a minimum reproducible schema of the bug.
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
# If possible, please paste your GraphQL query file,
# or a minimum reproducible query of the bug.
```
</details>

**Comment by vasilich6107** [comment]
If you are running codegen on github action please omit committing generated code into the repo

**Comment by Tahmeed27** [comment]
I wanted to run a github action that would fail if someone forgot to run codegen before pushing. But the codegen on github actions was generating a git diff even if they had run codegen before pushing. Would it not be possible to do this?

**Comment by vasilich6107** [comment]
I understand you but I do not know how code generation ordering affected by target platform.

Let's look at your problem.

You are trying to check if someone forgot to run codegen. So you run codegen on github action. You spend build time. And in case if one forgot it will get an error that he need to fix manually.

Look from the other side - do not commit generated code, run codegen in github action and it will not fail and will not disturb you in case if someone forgot to. There are other benefits of not committing the generated code - you'll not face the conflicts in generated code)

**Comment by vasilich6107** [comment]
Closing this issue cause maintaining generated code order is out of scope for the package
