### ISSUE TITLE
[example] Invalid example indentation in beta

### ISSUE THREAD

**Issue by ssssota** [comigor/artemis#327]
Hello! I found a typo in example.

https://github.com/comigor/artemis/blob/e029be16ccf765b3cdd5658969e268c1e5353225/example/graphbrainz/build.yaml#L13-L21

Invalid indentation at L14.

This commit is in https://github.com/comigor/artemis/commit/03c8efa168c076539a33b4d8bab3c36d3130c69d

**Comment by vasilich6107** [comment]
It seems that L14 is correct
Invalid all other lines

**Comment by vasilich6107** [comment]
Fixed
