### ISSUE TITLE
[Feature Request] Add Lint Ignore for Lower Camel Case

### ISSUE THREAD

**Issue by chillbrodev** [comigor/artemis#331]
## Description
When Artemis generates the code the files contain upper cased camel case variables. It would be great to add the lint ignore above them to disable the lint issue of Name non-constant identifiers using lowerCamelCase.dartnon_constant_identifier_names.

Please consider adding `// ignore: non_constant_identifier_names`. 

Thanks in advance.

## Specs
Artemis version: 7.0.0-beta.17

**Comment by vasilich6107** [comment]
Check read me for beta branch
There is `ignore_for_file` option to add whatever you need

**Comment by vasilich6107** [comment]
@chillbrodev any feedback?

**Comment by chillbrodev** [comment]
@vasilich6107 Heya, I just saw this comment. Been away from my desk. I'll give it a review and let you know. Thanks :D

**Comment by chillbrodev** [comment]
This will resolve my issue. Thanks. Closing this now.
