### ISSUE TITLE
Generate dart classes based on schema definitions

### ISSUE THREAD

**Issue by 1awaleed** [comigor/artemis#332]
I am wondering if `Artemis` is capable of generating types based on schema definitions? I cannot seem to find any documentation or related questions on this.

for example:

Given the following piece of scheme:
```dart
type Person {
    age: Int
    name: String!
}
```
Can it be converted to sound null safe dart class like this:
```dart
class Person{
  int? age;
  String name;

  Person({this.age, required this.name});

  Person.fromJson(Map<String, dynamic> json){
    age = json['age'];
    name = json['name'];
  }

  Map toJson(){
    Map _data = {};
    _data['age'] = age;
    _data['name'] = name;
    return _data;
  }
}
```

**Comment by vasilich6107** [comment]
What is the reason to do that conversion?
You could query different subset of fields so Artemis generates types based on what you are actually query and not basing on the fields that schema allows you to query.

artemis supports only generation based on queries/mutations

**Comment by vasilich6107** [comment]
@1awaleed any feedback?

**Comment by 24601** [comment]
> I am wondering if `Artemis` is capable of generating types based on schema definitions? I cannot seem to find any documentation or related questions on this.
> 
> for example:
> 
> Given the following piece of scheme:
> 
> ```dart
> type Person {
>     age: Int
>     name: String!
> }
> ```
> 
> Can it be converted to sound null safe dart class like this:
> 
> ```dart
> class Person{
>   int? age;
>   String name;
> 
>   Person({this.age, required this.name});
> 
>   Person.fromJson(Map<String, dynamic> json){
>     age = json['age'];
>     name = json['name'];
>   }
> 
>   Map toJson(){
>     Map _data = {};
>     _data['age'] = age;
>     _data['name'] = name;
>     return _data;
>   }
> }
> ```

This is a bit of an anti-pattern in GraphQL, as one of the core assumptions/tenets of GraphQL is to allow nested join/fetch and (sub)selections of data types to reduce overfetch or multiple trips. If you have a query that queries Person with a selection set that is all the fields, you'll essentially get "Person" as a class, but that's a bit of a hack, the actual ethos of GraphQL and adopting it into your design/use is probably the "right" solution.

**Comment by vasilich6107** [comment]
Closing this issue as far as Artemis generates types only basing on queries/mutations/subscriptions.
