### ISSUE TITLE
Comparison with graphql_flutter/graphql package

### ISSUE THREAD

**Issue by lume-code** [comigor/artemis#335]
Hello,
I have been worked with both of these gql clients for a while now beside each other. I have some doubts about how this two should be used and for flutter newbies like me i think others could be confused at first as well, There are guides on internet on using both at the same time but it doesn't feels completely natural to me. Most important differences i could see was graphql_flutter supports cache and Artemis does code generation, right?
Are they supposed to be used beside each other? Any best practices or suggestion to use only one maybe?

**Comment by vasilich6107** [comment]
@ridyio

Did you get along with this article?
https://medium.com/@v.ditsyak/ultimate-toolchain-to-work-with-graphql-in-flutter-13aef79c6484

**Comment by vasilich6107** [comment]
To be short - `graphql_flutter` is a client
`Artemis` for code generation

**Comment by lume-code** [comment]
Thanks for response, yes i have read that article. The part that made me doubt if these two are meant to be used along each other was when calling a mutation:
```
Mutation(
    options: MutationOptions(
        document: CreateAddressMutation(
                variables: CreateAddressArguments(
                    title: "",
                    details: "",
                    lat: 10.1,
                    lng: 10.1))
            .document),
    builder: (
      RunMutation runMutation,
      QueryResult? result,
    ) {
      return ElevatedButton(
          onPressed: () {
            if (_formKey.currentState!.validate()) {
              runMutation({
                "title": "T",
                "details": "D",
                "lat": 10.1,
                "lng": 10.1
              });
            }
          },
          child: Text('Save'),
          ));
```
I couldn't find a way around having to pass the arguments twice maybe i did something wrong here.

**Comment by vasilich6107** [comment]
@ridyio check this
https://github.com/comigor/artemis/issues/314

**Comment by lume-code** [comment]
@vasilich6107 Thanks a lot, Got it now
