### ISSUE TITLE
Support grahphql codegen introspection schemas

### ISSUE THREAD

**Issue by jmoseley** [comigor/artemis#34]
When using graphql codegen and the `introspection` plugin, the JSON output has a root key of `schema`, but the artemis parser expects this object to be nested inside a root `data` object (I believe this is the result if you request the introspection schema from the server).

The error you see in my case is:

```
[SEVERE] artemis:artemis on lib/$lib$:

NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("__schema")
```

It shouldn't be too hard to support both formats in the parser.

An alternative solution might be to support fetching the schema from a server directly (similar to what is supported by graphql codegen). I am already using graphql codegen for another corner of this project, so it was convenient to use it for providing the introspection json for artemis to consume as well, but it would be much cleaner to configure artemis to fetch the schema from the server directly.

**Comment by comigor** [comment]
Hey @jmoseley!
Definitely it seems easy to support! I'll mark this as an enhancement.

I'm not sure about schema fetching because some people (like myself) could need tokens/certificates to hit their servers and/or not always you want the most up-to-date schema in your app (and you could trigger your own scripts if you want this kind of automation).

**Comment by jmoseley** [comment]
I agree that fetching the schema is hard. A method similar to how it is done by graphql codegen might work, but that is a bunch of extra complexity. I pushed a PR for a really simple change, just to support both. The other option would be to make it configurable, but I'm not sure how many other shapes this schema might come in, so probably not worth it.

**Comment by comigor** [comment]
Yeha, I think this solution is enough, at least for now. Thanks!
