### ISSUE TITLE
Upgrade packages

### ISSUE THREAD

**Issue by fryette** [comigor/artemis#351]
Could you please upgrade json_annotation and json_serializable versions to the latest?

**Comment by vasilich6107** [comment]
No luck
```
Because source_gen >=1.1.0 depends on analyzer ^2.1.0 and gql_code_builder >=0.2.0-alpha+1621196644774 depends on analyzer ^1.2.0, source_gen >=1.1.0 is incompatible with gql_code_builder >=0.2.0-alpha+1621196644774.
So, because artemis depends on both gql_code_builder ^0.2.0 and source_gen ^1.1.0, version solving failed.
```

**Comment by mdrideout** [comment]
For the short term, the dependency override for analyzer is working fine for me. 

```yaml
dependency_overrides:
  analyzer: ^2.1.0
```

**Comment by vasilich6107** [comment]
Pub dev does not allow to publish with deps overrides

**Comment by vasilich6107** [comment]
@fryette I did the PR
https://github.com/gql-dart/gql/pull/268

**Comment by vasilich6107** [comment]
@fryette my pr was merged but there was an issue with auto release)
Waiting while they will fix it.
Check comments under PR

**Comment by fryette** [comment]
Great!
Thanks, will wait

**Comment by vasilich6107** [comment]
@fryette this is nightmare to get support from gql team...
They merged my PR but failed the release. And now no one knows what to do...
I released temp `gql_code_builder2` to update the packages)
Have fun
