### ISSUE TITLE
There isn’t a setter named 'stringify' in class 'EquatableMixin'

### ISSUE THREAD

**Issue by Niravoo7** [comigor/artemis#353]
In autogenerate *.graphql.g.dart file, we are facing this issue. which says 'There isn’t a setter named 'stringify' in class 'EquatableMixin''. Try correcting the name to reference an existing setter, or declare the setter.

i am using Artemis version: '7.1.1-beta.1'. and i tried with '7.0.0-beta.17' version also. but In that facing same issue.

![Screenshot 2021-10-06 at 1 02 11 PM](https://user-images.githubusercontent.com/32232529/136160935-42856c7f-1a23-430f-9d13-d6979bdc069c.png)

In build.yaml file
-----------------
                    - output: lib/graphql/queries/updateAgreement.graphql.dart
                      schema: graphql/schema.graphql
                      queries_glob: graphql/queries/updateAgreement.graphql

output of ->flutter pub run build_runner build --verbose
--------------------------------------------------------
imac@192 flutter-app % flutter pub run build_runner build --verbose
[  +89 ms] executing: sysctl hw.optional.arm64
[  +15 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +5 ms] executing: [/Users/imac/Desktop/sdk/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +19 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[        ] executing: [/Users/imac/Desktop/sdk/flutter/flutter/] git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[ +148 ms] Exit code 0 from: git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[   +2 ms] 2.5.2
[   +8 ms] executing: [/Users/imac/Desktop/sdk/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/imac/Desktop/sdk/flutter/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [/Users/imac/Desktop/sdk/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +11 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D64
[  +58 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +31 ms] Using /Users/imac/Desktop/sdk/flutter/flutter/.pub-cache for the pub cache.
[        ] executing: /Users/imac/Desktop/sdk/flutter/flutter/bin/cache/dart-sdk/bin/pub run build_runner build --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 558ms

[WARNING] build.fallback:
The package `tejimandi` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 783ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.7s

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 72ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 459ms

[INFO] Build:Succeeded after 542ms with 0 outputs (0 actions)

[+7047 ms] "flutter run" took 7,154ms.
[ +173 ms] ensureAnalyticsSent: 169ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by vasilich6107** [comment]
@Niravoo7 could you fill up the issue properly
You did not provide your schema and query.
This will help us to reproduce and fix quicker
Also attach your full `build.yaml` with all configuration options

**Comment by fredericbirke** [comment]
I have the same issue with the following setup:
Schema:
```graphql
type Mutation {
    loginKitchen(kitchenPassword: String!, restaurantId: UUID!): Boolean!
}
```

Mutation:
```graphql
mutation loginKitchen($restaurantId: UUID!, $password: String!) {
    loginKitchen(restaurantId: $restaurantId, kitchenPassword: $password)
}
```

build.yaml:
```yaml
targets:
  $default:
    sources:
      - lib/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/sifos_client/sifos_api.dart
              schema: schema.graphql
              queries_glob: lib/**.graphql
          scalar_mapping:
            - graphql_type: UUID
              dart_type: String
```

Packages:
```yaml
dependencies:
  artemis: 7.2.0-beta.0
  json_annotation: ^4.1.0
  equatable: ^2.0.3
  meta: ^1.5.0
  gql: '>=0.12.3 <1.0.0'

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.0
```

To me this seems like to be a bug in the generator? Im not sure, why those lines here are generated anyway:
![Screenshot 2021-10-12 at 10 18 37](https://user-images.githubusercontent.com/9481836/136919000-99d18c12-5943-41c9-897c-dca4e864e344.png)


After removing the marked lines in the screenshot, the client works without a problem.
If I can provide any further information, you might need, just say so :)

**Comment by fredericbirke** [comment]
The problem seems to be that the generator lets the data classes extend from `JsonSerializable with EquatableMixin` and then tries to handle the properties of the `EquatableMixin` as graphql fields as well.

Seems like the generator simply needs to ignore the properties of the [EquatableMixin](https://pub.dev/documentation/equatable/latest/equatable/EquatableMixin-mixin.html) when generating the types.

**Comment by maestrolsj** [comment]
i have the same issue

**Comment by vasilich6107** [comment]
hi @fredericbirke 
I tried to reproduce your issue
Check https://github.com/artflutter/graphql_toolchain/tree/artemis-%23353

Try it yourself - and you will see that there is no such issue
If you will be able to reproduce the issue on that project - make a PR

**Comment by vasilich6107** [comment]
@maestrolsj it would be great if you could provide reproduction github project
I tried to reproduce it by @fredericbirke example without any luck
Do not forget to update libs to latest versions

**Comment by vasilich6107** [comment]
Hi @fredericbirke @maestrolsj could you provide a github repo with reproduction of the bug?

**Comment by vasilich6107** [comment]
Closing the issue due to the lack of response
