### ISSUE TITLE
Interface implementing other interfaces is not supported

### ISSUE THREAD

**Issue by tlvenn** [comigor/artemis#383]
## Bug description
It seems that Artemis is not currently supporting schema with interface implementing other interfaces.
It currently errors out with
```
Unknown definition type 'implements'
interface NonDependantUser implements Node & Person & User {
```

## Specs
Artemis version: 7.6.2-beta

**Comment by vasilich6107** [comment]
@tlvenn it is not an artemis issue
subscribe to updates on this issue https://github.com/gql-dart/gql/issues/269

**Comment by tlvenn** [comment]
Ha thanks for the info @vasilich6107 !
