### ISSUE TITLE
build_runner fails citing null-safety error on `gql-code-builder` dependency

### ISSUE THREAD

**Issue by ecoant** [comigor/artemis#386]
**Before reporting a bug, please test the beta branch!**

## Bug description
Overnight a Codemagic (ci server) build started failing with the same dependencies in our pure dart project due to a null-safety issue in `gql_code_builder-0.3.0-alpha+1635885531709/`.

```
[WARNING] ../../../.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.3.0-alpha+1635885531709/lib/src/ast.dart:618:12: Error: A non-null value must be returned since the return type 'Expression' doesn't allow null.

 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/code_builder-4.1.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Precompiling build script... completed, took 11.0s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

To further complicate the issue, the same command in the same project with the same dependencies works totally fine.

I have filed an issue within the code-builder-gql project as well, since that is where the error points to, but I'm unable to place the cause of what appears to be a change in package content. Thank you!

https://github.com/gql-dart/gql/issues/308

## Specs
Artemis version: ^7.4.0-beta
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: lib/schema.graphql
              queries_glob: lib/graphql/**.graphql
          scalar_mapping:
            - graphql_type: Date
              dart_type: DateTime
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 845ms

[INFO] Bootstrap:Precompiling build script......
[WARNING] Bootstrap:
../../../.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.3.0-alpha+1635885531709/lib/src/ast.dart:618:12: Error: A non-null value must be returned since the return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/code_builder-4.1.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Bootstrap:Precompiling build script... completed, took 19.8s

[SEVERE] Bootstrap:
Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.



Build failed :|
```

**Comment by chillbrodev** [comment]
I thumbs up'd above. This is also a blocker for my current project.

**Comment by ekremkenter** [comment]
Same here, locking versions to `gql: 0.13.1-alpha+1645425888336` and `artemis: 7.5.0-beta` fixed for me. Probably it's related with gql's latest version not compatible with artemis.

**Comment by Saurabh-Detharia** [comment]
As a temporary solution, using the fixed version for the gql issue can be solved, like `gql: 0.13.0`.

**Comment by vasilich6107** [comment]
Updated code_builder and gql packages to latest stable versions
wait for v7.7.0 to be released

**Comment by chillbrodev** [comment]
The above solution worked!!! 

Here are my dependency overrides + other packages for anyone else facing this issue.

```
dependency_overrides:
  gql_code_builder: 0.5.0
  gql_exec: 0.4.0
  test_api: 0.4.9
  gql: 0.13.0
  ```
  
  packages:
  ```
  json_annotation: ^4.4.0
  artemis: ^7.3.2-beta
  equatable: ^2.0.3
  ```
  
dev dependencies:
```
build_runner: ^2.1.4
json_serializable: ^6.1.5
```

**Comment by ecoant** [comment]
> The above solution worked!!!
> 
> Here are my dependency overrides + other packages for anyone else facing this issue.
> 
> ```
> dependency_overrides:
>   gql_code_builder: 0.5.0
>   gql_exec: 0.4.0
>   test_api: 0.4.9
>   gql: 0.13.0
> ```
> 
> packages:
> 
> ```
> json_annotation: ^4.4.0
> artemis: ^7.3.2-beta
> equatable: ^2.0.3
> ```
> 
> dev dependencies:
> 
> ```
> build_runner: ^2.1.4
> json_serializable: ^6.1.5
> ```

Thank you!! This worked for me as well. I didn't know you could override package dependency versions like that - awesome!
