### ISSUE TITLE
Add support for analyzer 4.0

### ISSUE THREAD

**Issue by fabis94** [comigor/artemis#390]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/938316/168884602-a19ff0c1-fc6f-49a9-8fe3-7f2485d81e64.png">

Analyzer 4.0 is required to lint Dart 2.17 new features like Enhanced Enums, but Artemis relies on an older version

**Comment by vasilich6107** [comment]
Most likely you’ll need to ping gql team to add support 
Cause Artemis itself is pretty easy to update

**Comment by vasilich6107** [comment]
@fabis94 
if you'll check https://github.com/comigor/artemis/blob/beta/pubspec.yaml there is no analyzer dependancy at all in artemis package)

**Comment by vasilich6107** [comment]
It is transitive dependency from 
https://github.com/gql-dart/gql/blob/master/codegen/gql_code_builder/pubspec.yaml#L8

**Comment by vasilich6107** [comment]
It took several month for me prev time to bump the ananlyzer version
https://github.com/gql-dart/gql/pull/268

**Comment by namanshergill** [comment]
https://github.com/gql-dart/gql/pull/328

@vasilich6107 Seems like it has been updated

**Comment by vasilich6107** [comment]
#400 is on the way.
It is blocked by updating pipeline dart version)

**Comment by vasilich6107** [comment]
Updated, check latest version
