### ISSUE TITLE
flutter artemis : No file generated in my folder

### ISSUE THREAD

**Issue by tazik561** [comigor/artemis#398]
I am trying to generate against any graphql schema by artemis:

      artemis: ^7.9.0-beta
      dev_dependencies:
      freezed: ^2.0.0
      json_serializable: ^6.3.2
      build_runner: ^2.2.1

My build.yaml

    targets:
      $default:
        sources:
          - $package$
          - lib/**
          - graphql/**
          - integration_test/**.dart
        builders:
          artemis:
            options:
              fragments_glob: graphql/fragments/*.graphql
              schema_mapping:
                - output: lib/graphql_api/graphql_api.dart
                  schema: graphql/schema.graphql
                  queries_glob: graphql/queries/*.graphql
              scalar_mapping:
                - custom_parser_import: 'package:***/utils/coercers.dart'
                  graphql_type: DateTime
                  dart_type: DateTime
                - custom_parser_import: 'package:***/utils/coercers.dart'
                  graphql_type: Date
                  dart_type: DateTime
                - graphql_type: Timezone
                  dart_type: String
                - graphql_type: Money
                  dart_type: double

But after running `flutter pub run build_runner build --delete-conflicting-outputs` no file is generated in `queries folder? and I did not get errors in terminal

**Comment by vasilich6107** [comment]
Create reproduction repository please

**Comment by vasilich6107** [comment]
No feedback, no schema, no reproduction 
Closing the issue
Feel free to reopen
