### ISSUE TITLE
Generated graphql.dart creates an unnecessary top level variables

### ISSUE THREAD

**Issue by rirjkl19** [comigor/artemis#412]
Hi I have a quesstion.

I have mutation to login:

```
mutation Login($login: LoginInput!) {
  login(input: $login)
}
```

and the `*.graphql.dart` is properly created. However upon checking on the code it generates. It also generated a 

`final LOGIN_MUTATION_DOCUMENT_OPERATION_NAME = 'Login';`
`final LOGIN_MUTATION_DOCUMENT = DocumentNode(definitions: [...`

Which is not used to begin with by the package. I also don't see any use case on using this. How can I omit it as it could affect dart analysis auto completion.

**Comment by vasilich6107** [comment]
use property setting to disable
<img width="868" alt="image" src="https://github.com/comigor/artemis/assets/6721286/e1d4faff-57f1-4888-b43c-f02ef7bcb349">
