### ISSUE TITLE
Add support of http package version ^1.0.0

### ISSUE THREAD

**Issue by fryette** [comigor/artemis#417]
Most of the packages already migrated to newest version of http package.
Now it's impossible to use Artemis together with any package that have a reference on http package version ^1.0.0.

Could you please upgrade it?

Thanks in advance!

**Comment by Thelm76** [comment]
I began a PR here : #421 but it seems like tests are failing...

**Comment by fryette** [comment]
hope author will take a look

**Comment by comigor** [comment]
Hello @fryette and @Thelm76

As per [notice](https://github.com/comigor/artemis#notice) this project has been discontinued. Please feel free to fork this repo and [reference it directly](https://dart.dev/tools/pub/dependencies#git-packages) in your project or use one of the suggested alternatives.
