### ISSUE TITLE
Sharing fragments between queries

### ISSUE THREAD

**Issue by oakesja** [comigor/artemis#52]
Is it possible to share fragments between queries? 

For example if I have a fragment and two queries that use it...

```gql
fragment Category on JobCategory {
  id
  name
}
```

```gql 
query fetchInformationToCreateJobs($divisionId: Int!) {
  jobCategories(divisionId: $divisionId) {
    ...JobCategory
  }
}
```

```gql 
query prefetcher($divisionId: Int!) {
  jobCategories(divisionId: $divisionId) {
    ...JobCategory
  }
  division(id: $divisionId) {
     id 
     name
  }
}
```

If I place the fragment one of the queries or the other I get the following error message: 
```
[SEVERE] artemis:artemis on lib/$lib$:

Bad state: No element
dart:collection                                                         ListMixin.firstWhere
package:artemis/generator.dart 290:16                                   _extractClasses.<fn>
dart:core                                                               Iterable.forEach
package:artemis/generator.dart 306:10                                   _extractClasses
package:artemis/generator.dart 320:15                                   _extractClasses.<fn>.<fn>
package:artemis/generator.dart 159:20                                   _createClassProperty
package:artemis/generator.dart 206:10                                   _selectionToClassProperty
package:artemis/generator.dart 308:20                                   _extractClasses.<fn>
dart:core                                                               Iterable.forEach
package:artemis/generator.dart 306:10                                   _extractClasses
package:artemis/generator.dart 98:19                                    generateQuery
package:artemis/generator.dart 21:21                                    generateLibrary.<fn>
dart:_internal                                                          ListIterable.toList
package:artemis/generator.dart 22:8                                     generateLibrary
package:artemis/builder.dart 75:29                                      GraphQLQueryBuilder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 478:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 476:23           _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 434:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 430:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 378:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 377:36           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 323:20           _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 184:15  _NoOpBuildPerformanceTracker.trackBuildPhase
package:build_runner_core/src/generate/build_impl.dart 319:47           _SingleBuild._runPhases.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 313:32           _SingleBuild._runPhases
package:build_runner_core/src/logging/logging.dart 25:30                logTimedAsync
package:build_runner_core/src/generate/build_impl.dart 270:26           _SingleBuild._safeBuild.<fn>
dart:async                                                              runZoned
package:build_runner_core/src/generate/build_impl.dart 265:5            _SingleBuild._safeBuild
package:build_runner_core/src/generate/build_impl.dart 212:24           _SingleBuild.run
package:build_runner_core/src/generate/build_impl.dart 97:56            BuildImpl.run
package:build_runner_core/src/generate/build_runner.dart 25:14          BuildRunner.run
package:build_runner                                                    BuildCommand.run
package:args/command_runner.dart 197:27                                 CommandRunner.runCommand
package:args/command_runner.dart 112:25                                 CommandRunner.run.<fn>
dart:async                                                              new Future.sync
package:args/command_runner.dart 112:14                                 CommandRunner.run
package:build_runner                                                    run
.dart_tool/build/entrypoint/build.dart 31:22                            main
```

If I place the fragment in both of the queries I get: 
```
Exception: Two classes were generated with the same name `JobCategory`!
You may want to do either:
- Enable add_query_prefix on this schema_map
- Make queries_glob stricter, to gather less .graphql files on a single output
- Use alias on one of the places a `JobCategory` field is requested
```

I understand that it is possible to define two different schema mappings and have these generate to two different files. However, I would like the resultant fragment class to be independent of the queries like [apollo does](https://www.apollographql.com/docs/ios/fragments/)

**Comment by comigor** [comment]
Hello @oakesja! Sorry for the late reply,

Are those queries defined together in a single file? Have you  tried to set `add_query_prefix: true` in your build.yaml file?

But I see your point in having fragments generate its own class and be reusable thoroughly the queries. That's definitely a nice improvement that can be made!

**Comment by comigor** [comment]
I was thinking about making each fragment a mixin so that could be reused across other types but, looking closer, this change wouldn't solve your problem anyway.

Both your queries are using the same `jobCategories` resolver (which returna the same type: `JobCategory`). This approach conflicts on purpose because you could be querying another field from `JobCategory` outside of the fragment. Picture theses queries:
```graphql
fragment Category on JobCategory {
  id
  name
}

query fetchInformationToCreateJobs($divisionId: Int!) {
  jobCategories(divisionId: $divisionId) {
    ...JobCategory
    area
  }
}

query prefetcher($divisionId: Int!) {
  jobCategories(divisionId: $divisionId) {
    ...JobCategory
  }
  division(id: $divisionId) {
     id 
     name
  }
}
```

On `fetchInformationToCreateJobs` query, I also want the speculative field `area` of `JobCategory`, so three fields would be fetch (id, name, area); while on `prefetcher` query, I just want two fields (id, name). So that's make those two type different and as they share the same name, the generator breaks. That's why `add_query_prefix: true` will probably fix it for you, while still letting you use fragments.

**Comment by oakesja** [comment]
@comigor thanks for the reply back!  I will give the `add_query_prefix: true` and the new fragments as mixins a try and let you know how it goes. 

I definitely understand where you are coming from on the conflict if more selections are added outside the fragment. The apollo ios swift client gets around this by treating fragments separate from the rest of the data. So for the example above for the `fetchInformationToCreateJobs`: 
- `jobCategory.area` would work and return the area
- `jobCategory.name` would not work and instead you would use `jobCategory.fragments.category.name`

https://www.apollographql.com/docs/ios/fragments/

**Comment by oakesja** [comment]
👍  on `This would be even more useful, for instance, when concatenating multiple input files` in #53.  This allowed for the fragments to be shared in the same query but not across different queries, even with the `add_query_prefix: true`.

**Comment by comigor** [comment]
Yes, today is not possible to share fragments between queries on two different files. To do that, we need some kind of middleware; as we're discussing on https://github.com/comigor/artemis/issues/49.

So let's continue the conversation for this topic there, as it appears to be the same issue. Feel free to reopen this if you find it's needed! :)

**Comment by Gujie-Novade** [comment]
@comigor when you say [this](https://github.com/comigor/artemis/issues/52#issuecomment-554374118), does that mean that if a fragment is used at multiple places (even in the same file), it will never be possible to have a unique class for it?

**Comment by comigor** [comment]
Hey, @Gujie-Novade! What I've said there was implemented on `beta` branch: for some time now we generate fragments as mixins, and those mixins are generated only once for the file. Also, if you configure `fragments_glob`, you'll have globally-generated mixins/fragments as well.
