### ISSUE TITLE
Make enums loose

### ISSUE THREAD

**Issue by comigor** [comigor/artemis#58]
Today, it's always a breaking change to add a new option on a Enum on Artemis: the generated code will create an Enum based on the schema of on that code was generated, and if the server returns a new value on that enum, it will break with "ArgumentError".

To make enums retro-compatible, I suggest to (optionally) add an `UNKNOWN` value to every enum, and fallback to it on (well) unknown values.

**Comment by leoiacovini** [comment]
I would just try to use a more specific name than`UNKNOWN` given that this maybe a valid enum value in some cases. Maybe `ARTEMIS_UNKNOWN` or so.
