### ISSUE TITLE
Is there any option to remove operation name?

### ISSUE THREAD

**Issue by pd4d10** [comigor/artemis#59]
I'm using this lib with [GitHub GraphQL API](https://developer.github.com/v4/explorer/). Seems it does not support operation name and returns an error:

```json
{"errors":[{"message":"No operation named \"test\""}]}
```

**Comment by comigor** [comment]
Hello again @pd4d10!
Could you share more information on this? Which query are you trying to generate?

**Comment by pd4d10** [comment]
Thanks for the quick response!

This happens when I try to using it with [GitHub GraphQL API](https://developer.github.com/v4/explorer/). If the POST body contains `operationName`, for example:

```json
{
  "query":"{\n  viewer {\n    login\n  }\n}\n",
  "variables":null,
  "operationName":"test"
}
```

the query would fail.

I think this error is probably nothing to do with this lib. But if there is an option to remove `operationName` in generated code. it could be bypassed.

**Comment by pd4d10** [comment]
Tried to manually change generated dart code: Assign `null` to `operationName` and the query works.

```dart
// ...
  @override
  final String operationName = null;
// ...
```

**Comment by comigor** [comment]
Huh, that's weird. It seems GitHub is not accepting opertaionName field but, as an optional field, it shouldn't matter for the backend.

Today, Artemis use the query name for operationName, but it probably won't work with `null`.

Nevertheless, it seems that's a requirement for some using Artemis on some backends, and could be fixed. I just don't know what's the best way of doing this.

**Comment by pd4d10** [comment]
Found `serializer` param of `HttpLink`, which can be customize.

Code here: https://github.com/gql-dart/gql/blob/38805d34cb240ae5ccc67e3071b0b9d1b08bb4ed/gql_link/lib/src/request_serializer.dart

```dart
class MyRequestSerializer {
  const MyRequestSerializer();

  /// Serializes the request
  ///
  /// Extend this to add non-standard behavior
  Map<String, dynamic> serializeRequest(Request request) {
    final RequestExtensionsThunk thunk = request.context.entry();

    return <String, dynamic>{
      // "operationName": request.operation.operationName, // Comment this line
      "variables": request.variables,
      "query": printNode(request.operation.document),
      if (thunk != null) "extensions": thunk.getRequestExtensions(request),
    };
  }
}

final gqlClient = ArtemisClient.fromLink(
        HttpLink(
          'https://example.com/graphql',
          serializer: MyRequestSerializer(),
        ),
      );
```

**Comment by pd4d10** [comment]
I think this could be closed. Thanks!
