### ISSUE TITLE
Allow SDL files (.graphql) as schema files

### ISSUE THREAD

**Issue by lazylazyllama** [comigor/artemis#61]
If you use the graphql Playground, it is very easy do download the graphql schema as a .graphql file in the SDL format. This format is very clean an nice to use compared to the introspection schema which is annoying to query and so on..

So it would be very nice to support this.

#8 already mentioned something like this

**Comment by comigor** [comment]
Hey there @lazylazyllama!

Absolutely! I've started the project parsing the `.json` file because it was easier to parse in the code.

**Comment by klavs** [comment]
@comigor, I'm experimenting with code generation from GraphQL documents in https://github.com/gql-dart/gql/pull/15
It's not yet finished and it will not be compatible with artemis, but feel free to use or steel the code from there.

**Comment by vasilich6107** [comment]
I'm starting the implementation of this ticket)
I hope to finish fast. The main idea is to remove the intermediate representation of schema and move to the `gql` ast usage.

**Comment by comigor** [comment]
Oh nice, looking forward to this!

**Comment by klavs** [comment]
@vasilich6107 would you mind building it as a separate "introspection json to gql ast" package?

That way the community will be able to use it for their own use cases and Artemis would benefit from community giving feedback and improving your package.

**Comment by vasilich6107** [comment]
@klavs 
I do not see any use case from `introspection json -> gql` benefits in real life)
Personally I didn't know about the existence of JSON introspection before using `artemis` package. Could be my bad)

As I mentioned in my previous PR the JSON introspection usage + internal intermediate representation makes hard to support tests. This is the reason why I'm investing in this feature.

**Comment by vasilich6107** [comment]
#82
