### ISSUE TITLE
[feature request] Mark arguments as @required if they have an exclamation mark(non nullable)

### ISSUE THREAD

**Issue by vasilich6107** [comigor/artemis#67]
Hi. Thanks for you work.
I'd like to suggest an improvement.

I have a query

```
query SearchDestinationsData($pagination: PaginationInput!, $startsWith: Boolean!, $term: String!, $types: [DestinationType!]) {
    searchDestinations(pagination: $pagination, startsWith: $startsWith, term: $term, types: $types) {
        destinations {
            id
            name
            type
        }
        totalCount
    }
}
```

After generation I have corresponding class

```
class SearchDestinationsDataArguments extends JsonSerializable
    with EquatableMixin {
  SearchDestinationsDataArguments(
      {this.pagination, this.startsWith, this.term, this.types});

  ...
}
```

The arguments in constructor are not marked with `@required` annotation but they are definitely required according(marked with exclamation mark `PaginationInput!`) to the schema definition.

Expected result

```
SearchDestinationsDataArguments(
      {@required this.pagination, @required this.startsWith, @required this.term, this.types})
```

This will help to avoid unexpected errors.
Thanks

**Comment by comigor** [comment]
Hello @vasilich6107!

I've been planing to add non-nullable support to artemis as soon nnbd lands, but of course parts of it could be done without this wait (as seen, for instance on https://github.com/comigor/artemis/issues/13), hence your PR.

Thanks for taking the step and opening this issue and a PR improving the library!
