### ISSUE TITLE
generate single mixin for fragment

### ISSUE THREAD

**Issue by 2ZeroSix** [comigor/artemis#75]
#52 Issue with shared fragments is partially resolved in this PR: #65

But there is still a problem, new fragment mixin is generated for every query.
So you must use different output files for queries which use the same fragment.
This leading to the next problem: you can't use these mixins as base class for your fields in generated classes.

I hope the most appropriate solution would be to add `fragmets_output` field in `build.yaml` options and import this in queries output. (maybe also export(?))

**Comment by comigor** [comment]
Hey @2ZeroSix, sorry for taking too long to answer back :(

Hmm, that's a nice approach. I've just refactored this library a bit, and now on 4.0.0 a couple of things changed (but this behaviour didn't).

**Comment by comigor** [comment]
Hey @2ZeroSix,

Could you test `fragments_glob` on [beta branch](https://github.com/comigor/artemis/tree/beta) to see if it would be enough for this?

Feel free to reopen this issue if it's not!
