### ISSUE TITLE
Specify casing for generated Dart class names and properties

### ISSUE THREAD

**Issue by KieranLafferty** [comigor/artemis#77]
I'm working with a graphql endpoint that has both class names and property names come back in snake_case. This causes issues with Dart linter/compiler since it is expecting class names to be in PascalCase and properties to be in camelCase

Currently functionality generates as

```
@JsonSerializable(explicitToJson: true)
class group_mutation_response with EquatableMixin {
  group_mutation_response({this.returning_groups});

  factory group_mutation_response.fromJson(Map<String, dynamic> json) =>
      _$group_mutation_responseFromJson(json);

  List<group> returning_groups;

  @override
  List<Object> get props => [returning_groups];
  Map<String, dynamic> toJson() => _$group_mutation_responseToJson(this);
}
```

Ideally it would generate as 

```
@JsonSerializable(explicitToJson: true)
class GroupMutationResponse with EquatableMixin {          // <----- PascalCase
  GroupMutationResponse({this.returningGroups});

  factory GroupMutationResponse.fromJson(Map<String, dynamic> json) =>
      _$GroupMutationResponse(json);

  @JsonKey(name: 'returning_groups')  //  <---- Handle mapping to/from graphql json
  List<Group> returningGroups;  // <---- camelCase

  @override
  List<Object> get props => [returningGroups];
  Map<String, dynamic> toJson() => _$GroupMutationResponseToJson(this);  //  <---- PascalCase
}
```

Is there anything I can do to force the casing to generate using dart compatible casing?

**Comment by comigor** [comment]
Hey @KieranLafferty! 

Sorry for taking too long to answer back :(

Could you try it on 4.0.0 and see if the error persists?

**Comment by comigor** [comment]
I'm gonna close this but feel free to reopen if it's the case!

**Comment by ram231** [comment]
How do you add snake case field to camelCase in `build.yaml` file? there's a field called `is_available` boolean and I want to change it to isAvailable without toching the generated files.
