### ISSUE TITLE
How to resolve interface?

### ISSUE THREAD

**Issue by Theo6890** [comigor/artemis#97]
Hello,

I did not find any example with the artemis package on how to use the **type_name_field** argument in the build.yaml to resolve interface.
Does anyone have an idea on how to do it?

Thanks in advance.

**Comment by comigor** [comment]
Hello @Theo6890!

*type_name_field* is a configuration option to set which field will be used to resolve GraphQL types. By  default, its value is "__typename",  which is the default field GraphQL servers should use to resolve, as defined in the spec. Some servers, however, use "__resolveType" as this field name, and you should configure it accordingly to your server.

Aside from that, both [graphbrainz](https://github.com/comigor/artemis/tree/master/example/graphbrainz) and [github](https://github.com/comigor/artemis/tree/master/example/github) examples have queries that use interfaces and __typename field: [1](https://github.com/comigor/artemis/blob/master/example/graphbrainz/lib/queries/ed_sheeran.query.graphql#L3) [2](https://github.com/comigor/artemis/blob/master/example/github/lib/graphql/search_repositories.graphql#L4)

Feel free to reopen this if you have any other doubt!

**Comment by Theo6890** [comment]
I understood that the default value of GraphQL type_name_field can be either "__typename" or "__resolveType" but the thing is I have tried with both and it does not change anything I still can not resolve the interface to generate dart files.

I never use explicitly "__typename" or "__resolveType" in my .graphql files because I do not need it. In fact, on the server side I only use :

- For GraphQL schema :
`type MyObject1 implements ObjectInterface{
    add each fields of InterfaceType
    add specific fields of  MyObject1 
}`

- For Java Spring Boot server to resolve interface :
`if (env.getObject() instanceof MyObject1) return env.getSchema().getObjectType("MyObject1");`

So I do not really know what to do to resolve dart files generation problem. By the way the explicit error during the generation is : ` It is an union/interface of possible types {MyObject1: AllObjects$Query$ObjectInterface$MyObject1, MyObject2: AllObjects$Query$ObjectInterface$MyObject2, MyObject3: AllObjects$Query$ObjectInterface$MyObject3, MyObject4: AllObjects$Query$ObjectInterface$MyObject4, MyObject5: AllObjects$Query$ObjectInterface$MyObject5, MyObject6: AllObjects$Query$ObjectInterface$MyObject6}`

**Comment by comigor** [comment]
>I never use explicitly "__typename" or "__resolveType" in my .graphql files because I do not need it.

Maybe you don't need it directly, but any GraphQL client does need it to check which type of implementation of interface it falls for. Automatically inclusion of `__typename` field is something doable, but not implemented right now. I've created a card for that: https://github.com/comigor/artemis/issues/98

The fact that you don't have to explicit set __typename on the server is becaùse the very libraries do this automatically for you.

>So I do not really know what to do to resolve dart files generation problem. By the way the explicit error during the generation is

That's actually just a debugging log, not an error. If you take a look at the generated code, it should have some code like this: https://github.com/comigor/artemis/blob/master/example/graphbrainz/lib/queries/ed_sheeran.query.dart#L111-L118

And if it does, you just need to add `__typename` to your query on the interface selection set and it'd probably work!
