### ISSUE TITLE
Automatic insertion of __typename field to unions/interfaces selection set

### ISSUE THREAD

**Issue by comigor** [comigor/artemis#98]
Artemis needs the value of `__typename` field of union types and interfaces to be able to differentiate the object type when resolving those types. This means the user must add the type name field (tipically `__typename`) to the union type/interfaces they're querying.

Ideally, Artemis could automatically add this field to the query, avoiding this hassle.

**Comment by vasilich6107** [comment]
@comigor it seems that this issue if fixed by https://github.com/comigor/artemis/pull/254
